// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class accionSolicitada
{
    [Key]
    public int idAccion { get; set; }

    [Required]
    [StringLength(60)]
    public string nombre { get; set; }

    [StringLength(250)]
    public string descripcion { get; set; }

    public bool aplicaControlPedidos { get; set; }

    public bool aplicaProduccion { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idAccionNavigation")]
    public virtual ICollection<casoAccionSolicitada> casoAccionSolicitada { get; set; } = new List<casoAccionSolicitada>();
}