// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class areas
{
    [Key]
    public int idArea { get; set; }

    [StringLength(200)]
    public string nombreArea { get; set; }

    public int? secuencia { get; set; }

    [InverseProperty("tipoProcesoNavigation")]
    public virtual ICollection<auditoriaProceso> auditoriaProceso { get; set; } = new List<auditoriaProceso>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<familliaDeMaquina> familliaDeMaquina { get; set; } = new List<familliaDeMaquina>();

    [InverseProperty("tipoProcesoNavigation")]
    public virtual ICollection<fichaTecnicaProcesos> fichaTecnicaProcesos { get; set; } = new List<fichaTecnicaProcesos>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<horariosOperativos> horariosOperativos { get; set; } = new List<horariosOperativos>();

    [InverseProperty("areaAnteriorNavigation")]
    public virtual ICollection<procesoOf> procesoOfareaAnteriorNavigation { get; set; } = new List<procesoOf>();

    [InverseProperty("areaSiguienteNavigation")]
    public virtual ICollection<procesoOf> procesoOfareaSiguienteNavigation { get; set; } = new List<procesoOf>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<seccionDocumento> seccionDocumento { get; set; } = new List<seccionDocumento>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<tablerosOf> tablerosOf { get; set; } = new List<tablerosOf>();

    [InverseProperty("areaDestinoNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProcesoareaDestinoNavigation { get; set; } = new List<transferenciaProceso>();

    [InverseProperty("areaOrigenNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProcesoareaOrigenNavigation { get; set; } = new List<transferenciaProceso>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<turnosOperativosArea> turnosOperativosArea { get; set; } = new List<turnosOperativosArea>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();

    [InverseProperty("tipoProcesoNavigation")]
    public virtual ICollection<variablesTecnicas> variablesTecnicas { get; set; } = new List<variablesTecnicas>();
}