// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class areas
{
    [Key]
    public int idArea { get; set; }

    [StringLength(200)]
    public string nombreArea { get; set; }

    public int? secuencia { get; set; }

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<tablerosOf> tablerosOf { get; set; } = new List<tablerosOf>();

    [InverseProperty("idAreaNavigation")]
    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}