// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("oV", Name = "OV_ARTICULO_FK")]
public partial class articuloOv
{
    [Key]
    public int idArticulo { get; set; }

    public int? oV { get; set; }

    [StringLength(300)]
    public string articulo { get; set; }

    [StringLength(50)]
    public string unidad { get; set; }

    public string detalleArticulo { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? precioUnidad { get; set; }

    [StringLength(50)]
    public string lineaDeNegocio { get; set; }

    [StringLength(50)]
    public string departamento { get; set; }

    [ForeignKey("oV")]
    [InverseProperty("articuloOv")]
    public virtual oV oVNavigation { get; set; }
}