// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class auditoriaProceso
{
    [Key]
    public int idAuditoria { get; set; }

    public int? oF { get; set; }

    public int? idProceso { get; set; }

    public int? maquina { get; set; }

    [StringLength(50)]
    public string auditor { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    [StringLength(50)]
    public string supervisor { get; set; }

    [StringLength(10)]
    public string tipoImpresion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaAuditoria { get; set; }

    public int? estado { get; set; }

    public int? tipoProceso { get; set; }

    public string observaciones { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    public bool? archivado { get; set; }

    public bool? cancelado { get; set; }

    public int? tipoReporte { get; set; }

    public int? turnoAuditoria { get; set; }

    public bool? completo { get; set; }

    [ForeignKey("actualizadoPor")]
    [InverseProperty("auditoriaProcesoactualizadoPorNavigation")]
    public virtual usuario actualizadoPorNavigation { get; set; }

    [ForeignKey("auditor")]
    [InverseProperty("auditoriaProcesoauditorNavigation")]
    public virtual usuario auditorNavigation { get; set; }

    [ForeignKey("creadoPor")]
    [InverseProperty("auditoriaProcesocreadoPorNavigation")]
    public virtual usuario creadoPorNavigation { get; set; }

    [InverseProperty("idAuditoriaNavigation")]
    public virtual ICollection<detalleAuditoriaProceso> detalleAuditoriaProceso { get; set; } = new List<detalleAuditoriaProceso>();

    [ForeignKey("estado")]
    [InverseProperty("auditoriaProceso")]
    public virtual estadosReporte estadoNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("auditoriaProceso")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("auditoriaProceso")]
    public virtual maquinas maquinaNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("auditoriaProceso")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("auditoriaProcesooperadorNavigation")]
    public virtual usuario operadorNavigation { get; set; }

    [ForeignKey("supervisor")]
    [InverseProperty("auditoriaProcesosupervisorNavigation")]
    public virtual usuario supervisorNavigation { get; set; }

    [ForeignKey("tipoProceso")]
    [InverseProperty("auditoriaProceso")]
    public virtual areas tipoProcesoNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("auditoriaProceso")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }

    [ForeignKey("turnoAuditoria")]
    [InverseProperty("auditoriaProceso")]
    public virtual turnoAuditoria turnoAuditoriaNavigation { get; set; }
}