// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idReporteAuditoria", Name = "PROCESOS_FK")]
public partial class auditoriaDeProcesos
{
    [Key]
    public int idAuditoriaDeProcesos { get; set; }

    public int? idReporteAuditoria { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string bolsaDeTrabajo { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string referenciaImpresion { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string huellaTroquel { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string fichaTecnica { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string guiaDeColor { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string arteOPlotter { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string mecanicoODummy { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string calibre { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string lecturaDeArte { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string aprobacionDeArranque { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string codigoDeBarra { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string usoDeEspectro { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string identificacionDeProducto { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string tamanoDeMateriaPrima { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string curadoDeBarniz { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string pruebaDeCurado { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string tarimaPlastificada { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string contaminacion { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string fibra { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string arranqueDeFibra { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string adhesivoCorrecto { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string unidadesDeCorrugado { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string corrugadoIdentificado { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string corrugadoSellado { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string solicitudDeCorte { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string bobinaGolpeada { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string malOlor { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string delaminada { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string armadoDePieza { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string matrizSegunCalibre { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string escuadra { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string guiaDeCorte { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string malCortado { get; set; }

    [ForeignKey("idReporteAuditoria")]
    [InverseProperty("auditoriaDeProcesos")]
    public virtual reporteDeAuditoria idReporteAuditoriaNavigation { get; set; }
}