// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class base_nuevaContext : DbContext
{
    public base_nuevaContext(DbContextOptions<base_nuevaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<anexos_NEXO> anexos_NEXO { get; set; }

    public virtual DbSet<areas> areas { get; set; }

    public virtual DbSet<articuloOv> articuloOv { get; set; }

    public virtual DbSet<asignacion> asignacion { get; set; }

    public virtual DbSet<auxiliares> auxiliares { get; set; }

    public virtual DbSet<cargo> cargo { get; set; }

    public virtual DbSet<certificadoCalidad> certificadoCalidad { get; set; }

    public virtual DbSet<certificadoCalidad_Log> certificadoCalidad_Log { get; set; }

    public virtual DbSet<corridaCombinada> corridaCombinada { get; set; }

    public virtual DbSet<detalleCertificadoCalidad> detalleCertificadoCalidad { get; set; }

    public virtual DbSet<detalleCertificadoCalidad_Log> detalleCertificadoCalidad_Log { get; set; }

    public virtual DbSet<detalleEntrega> detalleEntrega { get; set; }

    public virtual DbSet<detalleFichaClientes> detalleFichaClientes { get; set; }

    public virtual DbSet<detalleFichaClientes_Log> detalleFichaClientes_Log { get; set; }

    public virtual DbSet<detalleReporte> detalleReporte { get; set; }

    public virtual DbSet<empleadoCatalogo> empleadoCatalogo { get; set; }

    public virtual DbSet<entregasProductoTerminado> entregasProductoTerminado { get; set; }

    public virtual DbSet<estadosOf> estadosOf { get; set; }

    public virtual DbSet<estadosReporte> estadosReporte { get; set; }

    public virtual DbSet<etiqueta> etiqueta { get; set; }

    public virtual DbSet<etiquetaOf> etiquetaOf { get; set; }

    public virtual DbSet<familliaDeMaquina> familliaDeMaquina { get; set; }

    public virtual DbSet<fichaTecnicaCliente> fichaTecnicaCliente { get; set; }

    public virtual DbSet<fichaTecnicaCliente_Log> fichaTecnicaCliente_Log { get; set; }

    public virtual DbSet<horariosOperativos> horariosOperativos { get; set; }

    public virtual DbSet<indisponibilidadMaquinas> indisponibilidadMaquinas { get; set; }

    public virtual DbSet<listaDeOperaciones> listaDeOperaciones { get; set; }

    public virtual DbSet<listaItem> listaItem { get; set; }

    public virtual DbSet<listaMaquina> listaMaquina { get; set; }

    public virtual DbSet<listasEmpaque> listasEmpaque { get; set; }

    public virtual DbSet<logCambiosOf> logCambiosOf { get; set; }

    public virtual DbSet<logCambiosProceso> logCambiosProceso { get; set; }

    public virtual DbSet<lotePliego> lotePliego { get; set; }

    public virtual DbSet<maquinas> maquinas { get; set; }

    public virtual DbSet<material> material { get; set; }

    public virtual DbSet<menu> menu { get; set; }

    public virtual DbSet<modulo> modulo { get; set; }

    public virtual DbSet<notasOf> notasOf { get; set; }

    public virtual DbSet<oV> oV { get; set; }

    public virtual DbSet<operaciones> operaciones { get; set; }

    public virtual DbSet<pausasMaquina> pausasMaquina { get; set; }

    public virtual DbSet<permiso> permiso { get; set; }

    public virtual DbSet<permisoEspecifico> permisoEspecifico { get; set; }

    public virtual DbSet<permisoMaquina> permisoMaquina { get; set; }

    public virtual DbSet<permisoTipo> permisoTipo { get; set; }

    public virtual DbSet<posturasOf> posturasOf { get; set; }

    public virtual DbSet<procesoAcabado> procesoAcabado { get; set; }

    public virtual DbSet<procesoAcabadoFlexo> procesoAcabadoFlexo { get; set; }

    public virtual DbSet<procesoBarniz> procesoBarniz { get; set; }

    public virtual DbSet<procesoImpresora> procesoImpresora { get; set; }

    public virtual DbSet<procesoImpresoraFlexo> procesoImpresoraFlexo { get; set; }

    public virtual DbSet<procesoMangaFlexo> procesoMangaFlexo { get; set; }

    public virtual DbSet<procesoOf> procesoOf { get; set; }

    public virtual DbSet<procesoPegadora> procesoPegadora { get; set; }

    public virtual DbSet<procesoPreprensa> procesoPreprensa { get; set; }

    public virtual DbSet<procesoSerigrafia> procesoSerigrafia { get; set; }

    public virtual DbSet<procesoTroqueladora> procesoTroqueladora { get; set; }

    public virtual DbSet<procesosFlexo> procesosFlexo { get; set; }

    public virtual DbSet<refreshToken> refreshToken { get; set; }

    public virtual DbSet<reportesDeOperadores> reportesDeOperadores { get; set; }

    public virtual DbSet<rol> rol { get; set; }

    public virtual DbSet<seccionDocumento> seccionDocumento { get; set; }

    public virtual DbSet<sesionOperador> sesionOperador { get; set; }

    public virtual DbSet<solicitudMateriales> solicitudMateriales { get; set; }

    public virtual DbSet<solicitudMaterialesOf> solicitudMaterialesOf { get; set; }

    public virtual DbSet<subModulo> subModulo { get; set; }

    public virtual DbSet<tablerosOf> tablerosOf { get; set; }

    public virtual DbSet<tarjetaEtiqueta> tarjetaEtiqueta { get; set; }

    public virtual DbSet<tarjetaOf> tarjetaOf { get; set; }

    public virtual DbSet<tipoDeObjetos> tipoDeObjetos { get; set; }

    public virtual DbSet<tipoReporte> tipoReporte { get; set; }

    public virtual DbSet<transferenciaProceso> transferenciaProceso { get; set; }

    public virtual DbSet<turnos> turnos { get; set; }

    public virtual DbSet<turnosOperativos> turnosOperativos { get; set; }

    public virtual DbSet<turnosOperativosArea> turnosOperativosArea { get; set; }

    public virtual DbSet<unidadesMedida> unidadesMedida { get; set; }

    public virtual DbSet<usuario> usuario { get; set; }

    public virtual DbSet<valeBobina> valeBobina { get; set; }

    public virtual DbSet<variableUnidadMedida> variableUnidadMedida { get; set; }

    public virtual DbSet<variablesTecnicas> variablesTecnicas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<anexos_NEXO>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__anexos_N__3214EC076FC81350");

            entity.Property(e => e.FechaSubida).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<areas>(entity =>
        {
            entity.HasKey(e => e.idArea).HasName("PK_AREAS");

            entity.Property(e => e.nombreArea).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<articuloOv>(entity =>
        {
            entity.HasKey(e => e.idArticulo).HasName("PK_ARTICULOOV");

            entity.Property(e => e.articulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.departamento).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleArticulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.lineaDeNegocio).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.unidad).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.oVNavigation).WithMany(p => p.articuloOv).HasConstraintName("FK_ARTICULO_OV");
        });

        modelBuilder.Entity<asignacion>(entity =>
        {
            entity.HasKey(e => e.idAsignacion).HasName("PK__asignaci__E1714478BB8AE70F");

            entity.Property(e => e.user).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.asignacion).HasConstraintName("FK_ASIGN_PROCESOO");

            entity.HasOne(d => d.userNavigation).WithMany(p => p.asignacion).HasConstraintName("FK_ASIGN_DISENADOR");
        });

        modelBuilder.Entity<auxiliares>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__auxiliar__3213E83F5C17182B");

            entity.Property(e => e.nombre).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<cargo>(entity =>
        {
            entity.HasKey(e => e.idCargo).HasName("PK_CARGO");

            entity.Property(e => e.descripcion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreCargo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<certificadoCalidad>(entity =>
        {
            entity.HasKey(e => e.idCertificadoCalidad).HasName("PK__certific__3110B5197AEA4595");

            entity.ToTable(tb => tb.HasTrigger("tr_certificadoCalidad_UPDATE_Log"));

            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.archivado).HasDefaultValue(false);
            entity.Property(e => e.cancelado).HasDefaultValue(false);
            entity.Property(e => e.elaboradoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.actualizadoPorNavigation).WithMany(p => p.certificadoCalidadactualizadoPorNavigation).HasConstraintName("FK_ACTUALIZA_CERTIFICADO");

            entity.HasOne(d => d.elaboradoPorNavigation).WithMany(p => p.certificadoCalidadelaboradoPorNavigation).HasConstraintName("FK_ELABORA_CERTIFICADO");

            entity.HasOne(d => d.idFichaClienteNavigation).WithMany(p => p.certificadoCalidad).HasConstraintName("FK_CERTIFICADO_FICHA");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.certificadoCalidad).HasConstraintName("FK_CERTIFICADO_OF");
        });

        modelBuilder.Entity<certificadoCalidad_Log>(entity =>
        {
            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.elaboradoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.fechaLog).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.tipoAccion).HasDefaultValue("UPDATE");
        });

        modelBuilder.Entity<corridaCombinada>(entity =>
        {
            entity.HasKey(e => e.idRelacion).HasName("PK__corridaC__FC68CFD3A8DB3F8F");

            entity.HasOne(d => d.maestroNavigation).WithMany(p => p.corridaCombinadamaestroNavigation)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_MAESTRO");

            entity.HasOne(d => d.subordinadoNavigation).WithOne(p => p.corridaCombinadasubordinadoNavigation).HasConstraintName("FK_SUBORDINADO");
        });

        modelBuilder.Entity<detalleCertificadoCalidad>(entity =>
        {
            entity.HasKey(e => e.idDetalle).HasName("PK__detalleC__6E19D6FA3406FD39");

            entity.ToTable(tb => tb.HasTrigger("tr_detalleCertificadoCalidad_UPDATE_Log"));

            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.idCertificadoCalidadNavigation).WithMany(p => p.detalleCertificadoCalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CERTIFICADO_CALIDAD");

            entity.HasOne(d => d.idUnidadNavigation).WithMany(p => p.detalleCertificadoCalidad).HasConstraintName("FK_CERTIFICADO_U_MEDIDA");

            entity.HasOne(d => d.idVariableNavigation).WithMany(p => p.detalleCertificadoCalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CERTIFICADO_VARIABLE");
        });

        modelBuilder.Entity<detalleCertificadoCalidad_Log>(entity =>
        {
            entity.Property(e => e.fechaLog).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.tipoAccion).HasDefaultValue("UPDATE");
        });

        modelBuilder.Entity<detalleEntrega>(entity =>
        {
            entity.HasKey(e => e.idDetalleEntrega).HasName("PK_DETALLEENTREGA");

            entity.Property(e => e.cliente).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.codArticuloSAP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreArticulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoEmpaque).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.unidad).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idEntregaPtNavigation).WithMany(p => p.detalleEntrega)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_DETALLE_ENTREGA");

            entity.HasOne(d => d.tipoEmpaqueNavigation).WithMany(p => p.detalleEntrega)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_EMPAQUE");
        });

        modelBuilder.Entity<detalleFichaClientes>(entity =>
        {
            entity.HasKey(e => e.idDetalle).HasName("PK__detalleF__6E19D6FAE127E0BD");

            entity.ToTable(tb => tb.HasTrigger("tr_detalleFichaClientes_UPDATE_Log"));

            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.idFichaClienteNavigation).WithMany(p => p.detalleFichaClientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FICHA_CLIENTES");

            entity.HasOne(d => d.idUnidadNavigation).WithMany(p => p.detalleFichaClientes).HasConstraintName("FK_DETALLE_FICHA_U_MEDIDA");

            entity.HasOne(d => d.idVariableNavigation).WithMany(p => p.detalleFichaClientes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VARIABLE_FICHACLIENTE");
        });

        modelBuilder.Entity<detalleFichaClientes_Log>(entity =>
        {
            entity.Property(e => e.fechaLog).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.tipoAccion).HasDefaultValue("UPDATE");
        });

        modelBuilder.Entity<detalleReporte>(entity =>
        {
            entity.HasKey(e => e.idDetalleReporte).HasName("PK_DETALLEREPORTE");

            entity.Property(e => e.bloqueada).HasDefaultValue(false);
            entity.Property(e => e.cliente).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.descripcion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idReporte).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.observaciones).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiroRetiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idMaterialNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_DETALLE_MATERIAL");

            entity.HasOne(d => d.idOperacionNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_DETALLE_OPERACION");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_R_PROCESOO");

            entity.HasOne(d => d.idReporteNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_DETALLE_REPORTE");

            entity.HasOne(d => d.idTransferenciaNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_TRANSFERENCIA_REPORTE");

            entity.HasOne(d => d.maquinaNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_MAQUINA_OPERACION_PROCESO");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.detalleReporte).HasConstraintName("FK_DETALLE_OF");
        });

        modelBuilder.Entity<empleadoCatalogo>(entity =>
        {
            entity.HasKey(e => e.idEmpleado).HasName("PK__empleado__5295297C2218DF95");

            entity.Property(e => e.idEmpleado).ValueGeneratedNever();
        });

        modelBuilder.Entity<entregasProductoTerminado>(entity =>
        {
            entity.HasKey(e => e.idEntregaPt).HasName("PK_ENTREGASPRODUCTOTERMINADO");

            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.areaEntrega).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.areaRecibe).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.creadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.entregadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.recibidoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idEstadoReporteNavigation).WithMany(p => p.entregasProductoTerminado).HasConstraintName("FK_ENTREGAS_ESTADO");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.entregasProductoTerminado).HasConstraintName("FK_ENTREGAS_MAQUINA");

            entity.HasOne(d => d.ofNavigation).WithMany(p => p.entregasProductoTerminado).HasConstraintName("FK_ENTREGAS_OF");
        });

        modelBuilder.Entity<estadosOf>(entity =>
        {
            entity.HasKey(e => e.idEstadoOf).HasName("PK_ESTADOSOF");

            entity.Property(e => e.nombreEstado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<estadosReporte>(entity =>
        {
            entity.HasKey(e => e.idEstadoReporte).HasName("PK_ESTADOSREPORTE");

            entity.Property(e => e.nombreEstado).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.tipoReporteNavigation).WithMany(p => p.estadosReporte).HasConstraintName("FK_TIPO_REPORTE");
        });

        modelBuilder.Entity<etiqueta>(entity =>
        {
            entity.HasKey(e => e.idEtiqueta).HasName("PK_ETIQUETA");

            entity.Property(e => e.color).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.texto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<etiquetaOf>(entity =>
        {
            entity.HasKey(e => e.idEtiquetaOf).HasName("PK_ETIQUETAOF");

            entity.HasOne(d => d.idEtiquetaNavigation).WithMany(p => p.etiquetaOf).HasConstraintName("FK_ETIQUETAS");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.etiquetaOf).HasConstraintName("FK_ETIQUETA_OF");
        });

        modelBuilder.Entity<familliaDeMaquina>(entity =>
        {
            entity.HasKey(e => e.idFamilia).HasName("PK_FAMILLIADEMAQUINA");

            entity.Property(e => e.nombreFamilia).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<fichaTecnicaCliente>(entity =>
        {
            entity.HasKey(e => e.idFichaCliente).HasName("PK__fichaTec__5CB71703E14AB9A5");

            entity.ToTable(tb => tb.HasTrigger("tr_fichaTecnicaCliente_UPDATE_Log"));

            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.archivado).HasDefaultValue(false);
            entity.Property(e => e.cancelado).HasDefaultValue(false);
            entity.Property(e => e.elaboradoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.version).HasDefaultValue(1);
            entity.Property(e => e.vigente).HasDefaultValue(true);

            entity.HasOne(d => d.actualizadoPorNavigation).WithMany(p => p.fichaTecnicaClienteactualizadoPorNavigation).HasConstraintName("FK_ACTUALIZA_FICHACLIENTE");

            entity.HasOne(d => d.elaboradoPorNavigation).WithMany(p => p.fichaTecnicaClienteelaboradoPorNavigation)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ELABORA_FICHACLIENTE");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.fichaTecnicaCliente).HasConstraintName("FK_FICHA_OF");
        });

        modelBuilder.Entity<fichaTecnicaCliente_Log>(entity =>
        {
            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.elaboradoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.fechaLog).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.tipoAccion).HasDefaultValue("UPDATE");
        });

        modelBuilder.Entity<horariosOperativos>(entity =>
        {
            entity.HasKey(e => e.idHorario).HasName("PK__horarios__DE60F33AFA2D1D3E");

            entity.Property(e => e.operador).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idAreaNavigation).WithMany(p => p.horariosOperativos).HasConstraintName("FK_AREA_HORARIO");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.horariosOperativos).HasConstraintName("FK_MAQUINA_HORARIO");

            entity.HasOne(d => d.operadorNavigation).WithMany(p => p.horariosOperativos).HasConstraintName("FK_HORARIO_USER");
        });

        modelBuilder.Entity<indisponibilidadMaquinas>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__indispon__3213E83F1C937E79");

            entity.Property(e => e.createdAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.indisponibilidadMaquinas).HasConstraintName("FK__indisponi__idMaq__7A521F79");
        });

        modelBuilder.Entity<listaDeOperaciones>(entity =>
        {
            entity.HasKey(e => e.idLista).HasName("PK__listaDeO__6C8A0FE5D17F6C83");
        });

        modelBuilder.Entity<listaItem>(entity =>
        {
            entity.HasKey(e => e.idListaItem).HasName("PK__listaIte__6688B8E42ED32F4F");

            entity.HasOne(d => d.idListaNavigation).WithMany(p => p.listaItem)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LISTA_DETALLE");

            entity.HasOne(d => d.idOperacionNavigation).WithMany(p => p.listaItem)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LISTA_OPERACION");
        });

        modelBuilder.Entity<listaMaquina>(entity =>
        {
            entity.HasKey(e => e.idListaMaquina).HasName("PK__listaMaq__836831C80664B053");

            entity.Property(e => e.alterna).HasDefaultValue(false);

            entity.HasOne(d => d.idListaNavigation).WithMany(p => p.listaMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LISTA_ASIGNACION");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.listaMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_LISTA_MAQUINA");
        });

        modelBuilder.Entity<listasEmpaque>(entity =>
        {
            entity.HasKey(e => e.idEmpaque).HasName("PK__listasEm__3AF2C2D965ECFF3E");

            entity.Property(e => e.idEmpaque).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.codigoSAP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.empaque).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<logCambiosOf>(entity =>
        {
            entity.HasKey(e => e.log_id).HasName("PK__logCambi__9E2397E0DEEB3C79");

            entity.Property(e => e.estado_anterior).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nuevo_estado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.usuario_id).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.logCambiosOf).HasConstraintName("FK_OF");

            entity.HasOne(d => d.usuario).WithMany(p => p.logCambiosOf).HasConstraintName("FK_USUARIO_LOG");
        });

        modelBuilder.Entity<logCambiosProceso>(entity =>
        {
            entity.HasKey(e => e.log_id).HasName("PK__logCambi__9E2397E0C8C6A3C6");

            entity.Property(e => e.estado_anterior).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nuevo_estado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.usuario_id).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.proceso).WithMany(p => p.logCambiosProceso)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PROCESO");

            entity.HasOne(d => d.usuario).WithMany(p => p.logCambiosProceso).HasConstraintName("FK_USUARIO");
        });

        modelBuilder.Entity<lotePliego>(entity =>
        {
            entity.HasKey(e => e.idLote).HasName("PK_LOTEPLIEGO");

            entity.Property(e => e.codigoBobinaSAP).UseCollation("Albanian_100_BIN");
            entity.Property(e => e.creadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tira).HasDefaultValue(false);

            entity.HasOne(d => d.creadoPorNavigation).WithMany(p => p.lotePliego).HasConstraintName("FK_CREADO_POR");

            entity.HasOne(d => d.idSolicitudNavigation).WithMany(p => p.lotePliego).HasConstraintName("FK_LOTEPLIEGO_SOLICITUD");

            entity.HasOne(d => d.procesoOrigenNavigation).WithMany(p => p.lotePliego).HasConstraintName("FK_LOTE_PROCESO_ORIGEN");
        });

        modelBuilder.Entity<maquinas>(entity =>
        {
            entity.HasKey(e => e.idMaquina).HasName("PK_MAQUINAS");

            entity.Property(e => e.nombreCorto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreMaquina).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idFamiliaNavigation).WithMany(p => p.maquinas).HasConstraintName("FK_MAQUINAS_FAMILIA");
        });

        modelBuilder.Entity<material>(entity =>
        {
            entity.HasKey(e => e.idMaterial).HasName("PK_MATERIAL");

            entity.Property(e => e.idMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e._base).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.calibre).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<menu>(entity =>
        {
            entity.HasKey(e => e.idMenu).HasName("PK_MENU");

            entity.Property(e => e.icono).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreMenu).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ruta).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<modulo>(entity =>
        {
            entity.HasKey(e => e.idModulo).HasName("PK_MODULO");

            entity.Property(e => e.nombreModulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idMenuNavigation).WithMany(p => p.modulo).HasConstraintName("FK_MODULO_MENU");
        });

        modelBuilder.Entity<notasOf>(entity =>
        {
            entity.HasKey(e => e.idComentario).HasName("PK__notasOf__C74515DAC72B3FC2");

            entity.Property(e => e.creadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.texto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoNota).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.notasOf)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("OF_FK");
        });

        modelBuilder.Entity<oV>(entity =>
        {
            entity.HasKey(e => e.oV1).HasName("PK_OV");

            entity.Property(e => e.oV1).ValueGeneratedNever();
            entity.Property(e => e.cliente).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.codigoCliente).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.comentario).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoOrden).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.vendedor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<operaciones>(entity =>
        {
            entity.HasKey(e => e.idOperacion).HasName("PK_OPERACIONES");

            entity.Property(e => e.nombreOperacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.prefijo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.sumativa).HasDefaultValue(false);
            entity.Property(e => e.tipoOperacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.familiaMaquinaNavigation).WithMany(p => p.operaciones).HasConstraintName("FK_FAMILIA_MAQUINA");
        });

        modelBuilder.Entity<pausasMaquina>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__pausasMa__3213E83F297D9027");

            entity.Property(e => e.bitacoraId).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoPausa).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.usuario).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.bitacora).WithMany(p => p.pausasMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("BITACORA_FK");

            entity.HasOne(d => d.maquinaNavigation).WithMany(p => p.pausasMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("MAQUINA_FK");

            entity.HasOne(d => d.usuarioNavigation).WithMany(p => p.pausasMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("USUARIO_FK");
        });

        modelBuilder.Entity<permiso>(entity =>
        {
            entity.HasKey(e => e.idPermiso).HasName("PK_PERMISO");

            entity.Property(e => e.descripcion).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idRolNavigation).WithMany(p => p.permiso)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PERMISO_ROL");

            entity.HasOne(d => d.idSubModuloNavigation).WithMany(p => p.permiso)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PERMISO_SUBMODULO");
        });

        modelBuilder.Entity<permisoEspecifico>(entity =>
        {
            entity.HasKey(e => e.idPermisoEspecifico).HasName("PK__permisoE__11805B4430FF764A");

            entity.HasOne(d => d.idPermisoTipoNavigation).WithMany(p => p.permisoEspecifico)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PERMISO_TIPO");

            entity.HasOne(d => d.idRolNavigation).WithMany(p => p.permisoEspecifico)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ROL");
        });

        modelBuilder.Entity<permisoMaquina>(entity =>
        {
            entity.HasKey(e => e.idPermisoMaquina).HasName("PK__permisoM__14AF841E56D0504E");

            entity.Property(e => e.user).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.maquinaNavigation).WithMany(p => p.permisoMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PERMISOS_MAQUINA");

            entity.HasOne(d => d.userNavigation).WithMany(p => p.permisoMaquina)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PERMISOS_MAQUINA_USUARIO");
        });

        modelBuilder.Entity<permisoTipo>(entity =>
        {
            entity.HasKey(e => e.idPermisoTipo).HasName("PK__permisoT__BA9D7CD3A8DDE3D3");

            entity.HasOne(d => d.idSubModuloNavigation).WithMany(p => p.permisoTipo)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SUBMODULO");
        });

        modelBuilder.Entity<posturasOf>(entity =>
        {
            entity.HasKey(e => e.idPostura).HasName("PK_POSTURASOF");

            entity.Property(e => e.nombrePostura).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idTableroNavigation).WithMany(p => p.posturasOf).HasConstraintName("FK_POSTURAS_TABLEROS");
        });

        modelBuilder.Entity<procesoAcabado>(entity =>
        {
            entity.Property(e => e.barniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadDemasia).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleBarniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleNum).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foil).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foilDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminadoDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.medidaProd).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.numerado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.retiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoCierre).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoAcabado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoAcabado_procesoOf");
        });

        modelBuilder.Entity<procesoAcabadoFlexo>(entity =>
        {
            entity.HasKey(e => e.idProcesoAcanadoFlexo).HasName("PK__procesoA__13DE4B6F5490DE7D");

            entity.Property(e => e.cantCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadMaterialSoli).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.etiquetaRollo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosTotales).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.z).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoAcabadoFlexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoAcabadoFlexo_procesoOf");
        });

        modelBuilder.Entity<procesoBarniz>(entity =>
        {
            entity.Property(e => e.anchoPliego).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadPliegosDemasia).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadPliegosImprimir).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleBarniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleNumerado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foil).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foilDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminadoDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.largoPliego).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.numerado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.repeticionPliegos).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.retiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tamanoAbierto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tintas).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoBarniz)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoBarniz_procesoOf");
        });

        modelBuilder.Entity<procesoImpresora>(entity =>
        {
            entity.Property(e => e.anchoPliego).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barnizDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadPliegosDemasia).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadPliegosImprimir).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.detalleNumerado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foil).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foilDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idTroquel).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacionImpresion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminadoDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.largoPliego).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.medidaProd).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.numerado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.repeticionPliegos).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.retiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tamanoAbierto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tintas).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoImpresora)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoImpresora_procesoOf");
        });

        modelBuilder.Entity<procesoImpresoraFlexo>(entity =>
        {
            entity.HasKey(e => e.idProcesoImpresoraFlexo).HasName("PK__procesoI__751EE56008093203");

            entity.Property(e => e.ajusteMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.anchoMM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.anchoMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.areaM2).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barnizDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadMaterialSoli).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadTintas).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.codigoMontaje).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.costuraMM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.desarrolloMM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.desarrolloPulg).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.diametroCore).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.etiquetaRollo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.excedente).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foil).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foilDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.forma).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.gapDesa).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.gapEje).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.imposicionDesarrollo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.imposicionEje).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.imposicionTotal).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminadoDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.largoMM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.layFlat).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.radesq).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.refMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosTotales).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.semicorte).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.sentidoSalida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tintasFlexo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.totalM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.z).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoImpresoraFlexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoImpresoraFlexo_procesoOf");
        });

        modelBuilder.Entity<procesoMangaFlexo>(entity =>
        {
            entity.HasKey(e => e.idProcesoMangaFlexo).HasName("PK__procesoM__E9EEA4A75491350E");

            entity.Property(e => e.cantCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadMaterialSoli).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.etiquetaRollo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosTotales).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.z).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoMangaFlexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoMangaFlexo_procesoOf");
        });

        modelBuilder.Entity<procesoOf>(entity =>
        {
            entity.HasKey(e => e.idProceso).HasName("PK_PROCESOOF");

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("trg_BloquearDetallesFinalizados");
                    tb.HasTrigger("trg_UpdateEstadoOf");
                    tb.HasTrigger("trg_UpdateTarjetaOf");
                });

            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cancelada).HasDefaultValue(false);
            entity.Property(e => e.comentario).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.descripcionOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idMaquinaSAP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreTarjeta).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.productoOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.programadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.reproceso).HasDefaultValue(false);
            entity.Property(e => e.serieNumeracion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoMaquinaSAP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiroRetiro).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.areaAnteriorNavigation).WithMany(p => p.procesoOfareaAnteriorNavigation).HasConstraintName("FK_AREA_SIGUENTE");

            entity.HasOne(d => d.areaSiguienteNavigation).WithMany(p => p.procesoOfareaSiguienteNavigation).HasConstraintName("FK_AREA_ANTERIOR");

            entity.HasOne(d => d.idMaterialNavigation).WithMany(p => p.procesoOf).HasConstraintName("FK_PROCESO_MATERIAL");

            entity.HasOne(d => d.idPosturaNavigation).WithMany(p => p.procesoOf).HasConstraintName("FK_PROCESO_POSTURA_");

            entity.HasOne(d => d.idSolicitudMaterialesNavigation).WithMany(p => p.procesoOf).HasConstraintName("FK_SOLICITUD_MATERIALES_PROCESO");

            entity.HasOne(d => d.idTableroNavigation).WithMany(p => p.procesoOf).HasConstraintName("FK_PROCESO_TABLERO");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.procesoOf).HasConstraintName("FK_PROCESO_OF");

            entity.HasOne(d => d.procesoAnteriorNavigation).WithMany(p => p.InverseprocesoAnteriorNavigation).HasConstraintName("FK_PROCESO_ANTERIOR");

            entity.HasOne(d => d.procesoSiguienteNavigation).WithMany(p => p.InverseprocesoSiguienteNavigation).HasConstraintName("FK_PROCESO_SIGUIENTE");
        });

        modelBuilder.Entity<procesoPegadora>(entity =>
        {
            entity.Property(e => e.cantidadAPegar).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoCierre).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoPegadora)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoPegadora_procesoOf");
        });

        modelBuilder.Entity<procesoPreprensa>(entity =>
        {
            entity.Property(e => e.cantidadPlanchas).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.medidaProd).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.ordenAnterior).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.repeticionPliegos).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tamanoAbierto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoPreprensa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoPreprensa_procesoOf");
        });

        modelBuilder.Entity<procesoSerigrafia>(entity =>
        {
            entity.HasKey(e => e.idProcesoSerigrafia).HasName("PK__procesoS__0D76A68B511ACF82");

            entity.Property(e => e.cantProducir).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoSerigrafia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoSerigrafia_procesoOf");
        });

        modelBuilder.Entity<procesoTroqueladora>(entity =>
        {
            entity.Property(e => e.cantPliegosTroquelar).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadPliegosDemasia).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.idTroquel).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.indicacion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.repeticionPliegos).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesoTroqueladora)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesoTroqueladora_procesoOf");
        });

        modelBuilder.Entity<procesosFlexo>(entity =>
        {
            entity.HasKey(e => e.idProcesosFlexo).HasName("PK__procesos__CBFD21756F84ADA7");

            entity.Property(e => e.barniz).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.barnizDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.cantidadMaterialSoli).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.diametroCore).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.etiquetaRollo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foil).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.foilDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.laminadoDetalle).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosCorrugado).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.rollosTotales).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoArreglo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tiempoCorrida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tintasFlexo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.totalM).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.z).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.procesosFlexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_procesosFlexo_procesoOf");
        });

        modelBuilder.Entity<refreshToken>(entity =>
        {
            entity.HasKey(e => e.token).HasName("PK_REFRESHTOKEN");

            entity.Property(e => e.token).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.refreshToken1).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.user).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.userNavigation).WithMany(p => p.refreshToken).HasConstraintName("FK_REFRESHT_USUARIO");
        });

        modelBuilder.Entity<reportesDeOperadores>(entity =>
        {
            entity.HasKey(e => e.idReporte).HasName("PK_REPORTESDEOPERADORES");

            entity.ToTable(tb => tb.HasTrigger("trg_BloquearDetalleReporte"));

            entity.Property(e => e.idReporte).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.archivado).HasDefaultValue(false);
            entity.Property(e => e.cancelado).HasDefaultValue(false);
            entity.Property(e => e.creadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.operador).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.turno).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.auxiliarNavigation).WithMany(p => p.reportesDeOperadores).HasConstraintName("FK_AUXILIAR_REPORTE");

            entity.HasOne(d => d.idEstadoReporteNavigation).WithMany(p => p.reportesDeOperadores).HasConstraintName("FK_REPORTES_ESTADO");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.reportesDeOperadores).HasConstraintName("FK_REPORTES_MAQUINA");

            entity.HasOne(d => d.idTipoReporteNavigation).WithMany(p => p.reportesDeOperadores).HasConstraintName("FK_REPORTES_TIPO");

            entity.HasOne(d => d.operadorNavigation).WithMany(p => p.reportesDeOperadores).HasConstraintName("FK_REPORTES_OPERADOR");
        });

        modelBuilder.Entity<rol>(entity =>
        {
            entity.HasKey(e => e.idRol).HasName("PK_ROL");

            entity.Property(e => e.descripcion).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreRol).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<seccionDocumento>(entity =>
        {
            entity.HasKey(e => e.idSeccion).HasName("PK__seccionD__94B87A7C7D6885E9");

            entity.Property(e => e.activo).HasDefaultValue(true);
            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ordenVisual).HasDefaultValue(1);

            entity.HasOne(d => d.idAreaNavigation).WithMany(p => p.seccionDocumento).HasConstraintName("FK_SECCION_AREA");

            entity.HasOne(d => d.tipoDocumentoNavigation).WithMany(p => p.seccionDocumento).HasConstraintName("FK_SECCION_DOCUMENTO");
        });

        modelBuilder.Entity<sesionOperador>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__sesionOp__3213E83F18D6E57D");

            entity.Property(e => e.bitacora).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.operador).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.turno).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.bitacoraNavigation).WithMany(p => p.sesionOperador)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_BITACORA");

            entity.HasOne(d => d.maquinaNavigation).WithMany(p => p.sesionOperador)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_MAQUINA");

            entity.HasOne(d => d.operadorNavigation).WithMany(p => p.sesionOperador)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OPERADOR");
        });

        modelBuilder.Entity<solicitudMateriales>(entity =>
        {
            entity.HasKey(e => e.idSolicitud).HasName("PK_SOLICITUDMATERIALES");

            entity.Property(e => e.idSolicitud).ValueGeneratedNever();
            entity.Property(e => e.archivado).HasDefaultValue(false);
            entity.Property(e => e.cancelado).HasDefaultValue(false);
            entity.Property(e => e.idMaterialSAP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<solicitudMaterialesOf>(entity =>
        {
            entity.HasKey(e => new { e.oF, e.idSolicitud }).HasName("PK_SOLICITUDMATERIALESOF");

            entity.HasOne(d => d.idSolicitudNavigation).WithMany(p => p.solicitudMaterialesOf)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOLICITU_OF");

            entity.HasOne(d => d.oFNavigation).WithMany(p => p.solicitudMaterialesOf)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OF_SOLICITUD");
        });

        modelBuilder.Entity<subModulo>(entity =>
        {
            entity.HasKey(e => e.idSubModulo).HasName("PK_SUBMODULO");

            entity.Property(e => e.nombreSubModulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idModuloNavigation).WithMany(p => p.subModulo).HasConstraintName("FK_SUBMODUL_MODULO");
        });

        modelBuilder.Entity<tablerosOf>(entity =>
        {
            entity.HasKey(e => e.idTablero).HasName("PK_TABLEROSOF");

            entity.Property(e => e.idSapMaquina).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreTablero).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idAreaNavigation).WithMany(p => p.tablerosOf).HasConstraintName("FK_TABLEROS_AREAS");

            entity.HasOne(d => d.idMaquinaNavigation).WithMany(p => p.tablerosOf).HasConstraintName("FK_TABLEROS_MAQUINA");
        });

        modelBuilder.Entity<tarjetaEtiqueta>(entity =>
        {
            entity.HasKey(e => e.idTarjetaEtiqueta).HasName("PK_TARJETAETIQUETA");

            entity.HasOne(d => d.idEtiquetaNavigation).WithMany(p => p.tarjetaEtiqueta).HasConstraintName("FK_TARJETA_ETIQUETAS");

            entity.HasOne(d => d.idProcesoNavigation).WithMany(p => p.tarjetaEtiqueta).HasConstraintName("FK_TARJETAE_TARJETAS");
        });

        modelBuilder.Entity<tarjetaOf>(entity =>
        {
            entity.HasKey(e => e.oF).HasName("PK_TARJETAOF");

            entity.Property(e => e.oF).ValueGeneratedNever();
            entity.Property(e => e.archivada).HasDefaultValue(false);
            entity.Property(e => e.cancelada).HasDefaultValue(false);
            entity.Property(e => e.clienteOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.codArticulo).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.descipcionOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.fsc).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.lineaDeNegocio).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombreOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.productoOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.seriesOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.tipoDeOrden).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.unidadMedida).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.vendedorOf).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idEstadoOfNavigation).WithMany(p => p.tarjetaOf).HasConstraintName("FK_TARJETA_ESTADO");
        });

        modelBuilder.Entity<tipoDeObjetos>(entity =>
        {
            entity.HasKey(e => e.idTipoDeObjetos).HasName("PK_TIPODEOBJETOS");

            entity.Property(e => e.nombreTipoDeObjeto).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<tipoReporte>(entity =>
        {
            entity.HasKey(e => e.idTipoReporte).HasName("PK_TIPOREPORTE");

            entity.Property(e => e.nombreTipoReporte).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<transferenciaProceso>(entity =>
        {
            entity.HasKey(e => e.idTransferencia).HasName("PK_TRANSFERENCIAPROCESO");

            entity.Property(e => e.enviadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.recibidoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.areaDestinoNavigation).WithMany(p => p.transferenciaProcesoareaDestinoNavigation).HasConstraintName("FK_AREA_DESTINO");

            entity.HasOne(d => d.areaOrigenNavigation).WithMany(p => p.transferenciaProcesoareaOrigenNavigation).HasConstraintName("FK_AREA_ORIGEN");

            entity.HasOne(d => d.enviadoPorNavigation).WithMany(p => p.transferenciaProcesoenviadoPorNavigation).HasConstraintName("FK_ENVIADO_POR");

            entity.HasOne(d => d.idDestinoNavigation).WithMany(p => p.transferenciaProcesoidDestinoNavigation).HasConstraintName("FK_TRANSFER_ID_DESTINO_OF");

            entity.HasOne(d => d.idLoteNavigation).WithMany(p => p.transferenciaProceso).HasConstraintName("FK_TRANSFER_LOTEPLIEG");

            entity.HasOne(d => d.idOrigenNavigation).WithMany(p => p.transferenciaProcesoidOrigenNavigation).HasConstraintName("FK_TRANSFER_ID_ORIGEN_OF");

            entity.HasOne(d => d.idProduccionNavigation).WithMany(p => p.transferenciaProceso).HasConstraintName("FK_PRODUCCION_ORIGEN");

            entity.HasOne(d => d.idSolicitudOrigenNavigation).WithMany(p => p.transferenciaProceso).HasConstraintName("FK_SOLICITUD_ORIGEN");

            entity.HasOne(d => d.oFDestinoNavigation).WithMany(p => p.transferenciaProceso).HasConstraintName("FK_OF_DESTINO");

            entity.HasOne(d => d.recibidoPorNavigation).WithMany(p => p.transferenciaProcesorecibidoPorNavigation).HasConstraintName("FK_RECIBIDO_POR");
        });

        modelBuilder.Entity<turnos>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__turnos__3213E83F597A9A98");

            entity.Property(e => e.turno).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<turnosOperativos>(entity =>
        {
            entity.HasKey(e => e.idTurno).HasName("PK__turnosOp__AA068B0188F0A7CC");
        });

        modelBuilder.Entity<turnosOperativosArea>(entity =>
        {
            entity.HasKey(e => e.idTurnoArea).HasName("PK__turnosOp__11A3B1E4E2EF661B");

            entity.HasOne(d => d.idAreaNavigation).WithMany(p => p.turnosOperativosArea).HasConstraintName("FK_AREA_TURNO");

            entity.HasOne(d => d.idTurnoNavigation).WithMany(p => p.turnosOperativosArea).HasConstraintName("FK_TURNO_OPE");
        });

        modelBuilder.Entity<unidadesMedida>(entity =>
        {
            entity.HasKey(e => e.idUnidad).HasName("PK__unidades__34C1E8D710E15920");

            entity.Property(e => e.activo).HasDefaultValue(true);
        });

        modelBuilder.Entity<usuario>(entity =>
        {
            entity.HasKey(e => e.user).HasName("PK_USUARIO");

            entity.Property(e => e.user).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.actualizadoPor).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.apellidos).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.email).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.nombres).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.password).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idAreaNavigation).WithMany(p => p.usuario).HasConstraintName("FK_USUARIO_AREA");

            entity.HasOne(d => d.idCargoNavigation).WithMany(p => p.usuario).HasConstraintName("FK_USUARIO_CARGO");

            entity.HasOne(d => d.idRolNavigation).WithMany(p => p.usuario).HasConstraintName("FK_USUARIO_ROL");
        });

        modelBuilder.Entity<valeBobina>(entity =>
        {
            entity.HasKey(e => e.idVale).HasName("PK__valeBobi__6738A580B7C04D00");

            entity.Property(e => e.idVale).ValueGeneratedNever();
            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.idMaterial).UseCollation("SQL_Latin1_General_CP1_CI_AS");

            entity.HasOne(d => d.idMaterialNavigation).WithMany(p => p.valeBobina).HasConstraintName("FK_VALE_MATERIAL");
        });

        modelBuilder.Entity<variableUnidadMedida>(entity =>
        {
            entity.HasKey(e => new { e.idVariable, e.idUnidad }).HasName("PK__variable__8C6A3E312364931C");

            entity.Property(e => e.predeterminada).HasDefaultValue(false);

            entity.HasOne(d => d.idUnidadNavigation).WithMany(p => p.variableUnidadMedida)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__variableU__idUni__5708E33C");

            entity.HasOne(d => d.idVariableNavigation).WithMany(p => p.variableUnidadMedida)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__variableU__idVar__5614BF03");
        });

        modelBuilder.Entity<variablesTecnicas>(entity =>
        {
            entity.HasKey(e => e.idVariable).HasName("PK__variable__EF2620BCC792F36B");

            entity.Property(e => e.activo).HasDefaultValue(true);
            entity.Property(e => e.certificadoCalidad).HasDefaultValue(false);
            entity.Property(e => e.fechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.fichaCliente).HasDefaultValue(false);
            entity.Property(e => e.fichaProceso).HasDefaultValue(false);
            entity.Property(e => e.fichaTecnica).HasDefaultValue(false);
            entity.Property(e => e.obligatorio).HasDefaultValue(false);
            entity.Property(e => e.ordenVisual).HasDefaultValue(1);

            entity.HasOne(d => d.idSeccionNavigation).WithMany(p => p.variablesTecnicas).HasConstraintName("FK_VARIABLE_SECCION");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}