// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCasoCalidad", "fecha", Name = "CASO_BITACORA_FK")]
public partial class bitacoraCaso
{
    [Key]
    public int idEvento { get; set; }

    public int idCasoCalidad { get; set; }

    public int idTipoEvento { get; set; }

    public string comentario { get; set; }

    public int? estadoAnterior { get; set; }

    public int? estadoNuevo { get; set; }

    [StringLength(50)]
    public string usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha { get; set; }

    [ForeignKey("estadoAnterior")]
    [InverseProperty("bitacoraCasoestadoAnteriorNavigation")]
    public virtual estadosReporte estadoAnteriorNavigation { get; set; }

    [ForeignKey("estadoNuevo")]
    [InverseProperty("bitacoraCasoestadoNuevoNavigation")]
    public virtual estadosReporte estadoNuevoNavigation { get; set; }

    [ForeignKey("idCasoCalidad")]
    [InverseProperty("bitacoraCaso")]
    public virtual casoCalidad idCasoCalidadNavigation { get; set; }

    [ForeignKey("idTipoEvento")]
    [InverseProperty("bitacoraCaso")]
    public virtual tipoEventoBitacora idTipoEventoNavigation { get; set; }
}