// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Keyless]
[Index("idProceso", Name = "FK_PROCESO_BOBINA")]
public partial class bobinasAsignadas
{
    public int? idProceso { get; set; }

    [StringLength(50)]
    public string codigoBobina { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? pesoInicial { get; set; }

    [StringLength(5)]
    public string codAlmacen { get; set; }

    [StringLength(50)]
    public string codMaterial { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? desperdicio { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? pesoFinal { get; set; }

    [ForeignKey("idProceso")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}