// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class camposPersonalizados
{
    [Key]
    public int idCampo { get; set; }

    [StringLength(200)]
    public string nombreCampo { get; set; }

    [StringLength(50)]
    public string tipo { get; set; }

    [StringLength(1)]
    public string valoresPosibles { get; set; }

    [InverseProperty("idCampoNavigation")]
    public virtual ICollection<tarjetaCampo> tarjetaCampo { get; set; } = new List<tarjetaCampo>();
}