// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class cargo
{
    [Key]
    public int idCargo { get; set; }

    [StringLength(100)]
    public string nombreCargo { get; set; }

    public string descripcion { get; set; }

    [InverseProperty("idCargoNavigation")]
    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}