// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEstado", Name = "ESTADO_CASO_FK")]
[Index("idCausaRaiz", Name = "IX_CASO_CAUSA_RAIZ")]
[Index("oF", "idEstado", Name = "OF_CASO_FK")]
[Index("idProceso", Name = "PROCESO_CASO_FK")]
[Index("responsable", Name = "RESPONSABLE_CASO_IDX")]
public partial class casoCalidad
{
    [Key]
    public int idCasoCalidad { get; set; }

    public int idTipoCaso { get; set; }

    [Required]
    [StringLength(20)]
    public string origen { get; set; }

    public int idEstado { get; set; }

    public int? idSeveridad { get; set; }

    public string descripcion { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? cantidadAfectada { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? cantidadRecuperable { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? cantidadNoRecuperable { get; set; }

    public int? idCategoriaDefecto { get; set; }

    public int? idSubtipoDefecto { get; set; }

    public int oF { get; set; }

    public int? idProceso { get; set; }

    [StringLength(100)]
    public string operador { get; set; }

    [StringLength(50)]
    public string registradoPor { get; set; }

    [StringLength(50)]
    public string responsable { get; set; }

    public string justificacionCierre { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaRegistro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCierre { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    public int tipoReporte { get; set; }

    public bool archivado { get; set; }

    public bool cancelado { get; set; }

    public int? idCausaRaiz { get; set; }

    public int? idResolucion { get; set; }

    public int? areaResponsable { get; set; }

    public int? cantidadDespachada { get; set; }

    public int? cantidadProduccion { get; set; }

    public int? unidadMedida { get; set; }

    [ForeignKey("actualizadoPor")]
    [InverseProperty("casoCalidadactualizadoPorNavigation")]
    public virtual usuario actualizadoPorNavigation { get; set; }

    [ForeignKey("areaResponsable")]
    [InverseProperty("casoCalidad")]
    public virtual areas areaResponsableNavigation { get; set; }

    [InverseProperty("idCasoCalidadNavigation")]
    public virtual ICollection<bitacoraCaso> bitacoraCaso { get; set; } = new List<bitacoraCaso>();

    [InverseProperty("idCasoCalidadNavigation")]
    public virtual ICollection<casoAccionSolicitada> casoAccionSolicitada { get; set; } = new List<casoAccionSolicitada>();

    [ForeignKey("idCategoriaDefecto")]
    [InverseProperty("casoCalidad")]
    public virtual categoriaDefecto idCategoriaDefectoNavigation { get; set; }

    [ForeignKey("idCausaRaiz")]
    [InverseProperty("casoCalidad")]
    public virtual causaRaizCalidad idCausaRaizNavigation { get; set; }

    [ForeignKey("idEstado")]
    [InverseProperty("casoCalidad")]
    public virtual estadosReporte idEstadoNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("casoCalidad")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("idResolucion")]
    [InverseProperty("casoCalidad")]
    public virtual resolucionCalidad idResolucionNavigation { get; set; }

    [ForeignKey("idSeveridad")]
    [InverseProperty("casoCalidad")]
    public virtual severidadCaso idSeveridadNavigation { get; set; }

    [ForeignKey("idSubtipoDefecto")]
    [InverseProperty("casoCalidad")]
    public virtual subtipoDefecto idSubtipoDefectoNavigation { get; set; }

    [ForeignKey("idTipoCaso")]
    [InverseProperty("casoCalidad")]
    public virtual tipoCaso idTipoCasoNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("casoCalidad")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [ForeignKey("registradoPor")]
    [InverseProperty("casoCalidadregistradoPorNavigation")]
    public virtual usuario registradoPorNavigation { get; set; }

    [ForeignKey("responsable")]
    [InverseProperty("casoCalidadresponsableNavigation")]
    public virtual usuario responsableNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("casoCalidad")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }

    [ForeignKey("unidadMedida")]
    [InverseProperty("casoCalidad")]
    public virtual unidadesMedida unidadMedidaNavigation { get; set; }
}