// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCasoCalidad", Name = "CASO_ACCION_FK")]
[Index("idCasoCalidad", "idAccion", Name = "CASO_ACCION_UQ", IsUnique = true)]
[Index("idEstado", Name = "ESTADO_ACCION_FK")]
public partial class casoAccionSolicitada
{
    [Key]
    public int idCasoAccion { get; set; }

    public int idCasoCalidad { get; set; }

    public int idAccion { get; set; }

    public int idEstado { get; set; }

    public int tipoReporte { get; set; }

    [StringLength(250)]
    public string comentario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaRegistro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [ForeignKey("idAccion")]
    [InverseProperty("casoAccionSolicitada")]
    public virtual accionSolicitada idAccionNavigation { get; set; }

    [ForeignKey("idCasoCalidad")]
    [InverseProperty("casoAccionSolicitada")]
    public virtual casoCalidad idCasoCalidadNavigation { get; set; }

    [ForeignKey("idEstado")]
    [InverseProperty("casoAccionSolicitada")]
    public virtual estadosReporte idEstadoNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("casoAccionSolicitada")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }
}