// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("codigo", Name = "UQ_CATALOGOFLAG_CODIGO", IsUnique = true)]
public partial class catalogoFlag
{
    [Key]
    public int idFlag { get; set; }

    [Required]
    [StringLength(30)]
    public string codigo { get; set; }

    [Required]
    [StringLength(80)]
    public string nombre { get; set; }

    [StringLength(250)]
    public string descripcion { get; set; }

    [Required]
    [StringLength(20)]
    public string efecto { get; set; }

    [Required]
    [StringLength(20)]
    public string modoAsignacion { get; set; }

    public bool requiereTexto { get; set; }

    public bool permiteQuitarManual { get; set; }

    [Required]
    [StringLength(60)]
    public string color { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idFlagNavigation")]
    public virtual ICollection<flagDocumento> flagDocumento { get; set; } = new List<flagDocumento>();

    [InverseProperty("idFlagNavigation")]
    public virtual ICollection<flagTipoDocumento> flagTipoDocumento { get; set; } = new List<flagTipoDocumento>();

    [InverseProperty("idFlagNavigation")]
    public virtual ICollection<tableroFlag> tableroFlag { get; set; } = new List<tableroFlag>();
}