// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class catalogoTipoPapel
{
    [Key]
    public int idTipoPapel { get; set; }

    [Required]
    [StringLength(150)]
    public string nombre { get; set; }

    public bool? activo { get; set; }

    [ForeignKey("idTipoPapel")]
    [InverseProperty("idTipoPapel")]
    public virtual ICollection<maquinas> idMaquina { get; set; } = new List<maquinas>();
}