// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class certificadoCalidad_Log
{
    [Key]
    public int idLog { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaLog { get; set; }

    [StringLength(50)]
    public string usuarioLog { get; set; }

    [StringLength(10)]
    public string tipoAccion { get; set; }

    public int idCertificadoCalidad { get; set; }

    public int? idFichaCliente { get; set; }

    public int? oF { get; set; }

    [StringLength(50)]
    public string elaboradoPor { get; set; }

    public DateOnly? fechaElaboracion { get; set; }

    public int? cantidadProducida { get; set; }

    public int? cantidadDespachada { get; set; }

    public DateOnly? fechaDespacho { get; set; }

    public DateOnly? fechaProduccion { get; set; }

    [StringLength(100)]
    public string creditoFiscal { get; set; }

    public string observaciones { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }
}