// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("oF", Name = "OF_CERTIFICADO_FK")]
public partial class certificadoDeCalidad
{
    [Key]
    public int idCertificado { get; set; }

    public int? oF { get; set; }

    [StringLength(10)]
    public string numeroDeLote { get; set; }

    [StringLength(100)]
    public string numeroFactura { get; set; }

    public int? numeroOv { get; set; }

    [StringLength(200)]
    public string cliente { get; set; }

    [StringLength(100)]
    public string codigoProducto { get; set; }

    [StringLength(254)]
    public string producto { get; set; }

    [StringLength(200)]
    public string tipoDeProducto { get; set; }

    public int? cantidadEntregada { get; set; }

    public int? cantidadDespachada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCertificado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaProduccion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaDespacho { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public string observaciones { get; set; }

    [StringLength(100)]
    public string creadoPor { get; set; }

    public int? tipoObjeto { get; set; }

    public int? version { get; set; }

    [InverseProperty("idCertificadoNavigation")]
    public virtual ICollection<detalleCertificado> detalleCertificado { get; set; } = new List<detalleCertificado>();

    [ForeignKey("oF")]
    [InverseProperty("certificadoDeCalidad")]
    public virtual tarjetaOf oFNavigation { get; set; }
}