// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
namespace Sistema_Produccion_3_Backend.Models;

[Index("idMotivo", Name = "MOTIVO_CONCILIACION_FK")]
[Index("idPreliminar", Name = "PRELIMINAR_CONCILIACION_UQ", IsUnique = true)]
public partial class conciliacion
{
    [Key]
    public int idConciliacion { get; set; }

    public int idPreliminar { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal cantidadPreliminar { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal cantidadTransferidaTotal { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? cantidadConfirmadaGenerada { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal diferencia { get; set; }

    public int? idMotivo { get; set; }

    public int? idDecision { get; set; }

    public string comentario { get; set; }

    [StringLength(50)]
    public string responsable { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaConciliacion { get; set; }

    public bool cancelado { get; set; }

    public bool archivado { get; set; }

    [ForeignKey("idDecision")]
    [InverseProperty("conciliacion")]
    public virtual decisionConciliacion idDecisionNavigation { get; set; }

    [ForeignKey("idMotivo")]
    [InverseProperty("conciliacion")]
    public virtual motivoConciliacion idMotivoNavigation { get; set; }

    [ForeignKey("idPreliminar")]
    [InverseProperty("conciliacion")]
    public virtual confirmacionPreliminar idPreliminarNavigation { get; set; }

    [ForeignKey("responsable")]
    [InverseProperty("conciliacion")]
    public virtual usuario responsableNavigation { get; set; }
}