// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idProceso", Name = "IDX_CI_PROCESO")]
public partial class condicionInicial
{
    [Key]
    public int idCondicionInicial { get; set; }

    public int idProceso { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(250)]
    public string justificación { get; set; }

    public bool? archivada { get; set; }

    public bool? cancelada { get; set; }

    [ForeignKey("creadoPor")]
    [InverseProperty("condicionInicialcreadoPorNavigation")]
    public virtual usuario creadoPorNavigation { get; set; }

    [InverseProperty("idCondicionInicialNavigation")]
    public virtual ICollection<detalleCondicionInicial> detalleCondicionInicial { get; set; } = new List<detalleCondicionInicial>();

    [ForeignKey("idProceso")]
    [InverseProperty("condicionInicial")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("condicionInicialoperadorNavigation")]
    public virtual usuario operadorNavigation { get; set; }
}