// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idProceso", Name = "PROCESO_CONFIG_FK")]
public partial class configuracionProceso
{
    [Key]
    public int idConfig { get; set; }

    public int? idProceso { get; set; }

    public int? tipoEntrada { get; set; }

    public int? tipoSalida { get; set; }

    public int? tipoComponente { get; set; }

    public bool? esEnsamblaje { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("configuracionProceso")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("tipoComponente")]
    [InverseProperty("configuracionProcesotipoComponenteNavigation")]
    public virtual tipoComponente tipoComponenteNavigation { get; set; }

    [ForeignKey("tipoEntrada")]
    [InverseProperty("configuracionProcesotipoEntradaNavigation")]
    public virtual tipoComponente tipoEntradaNavigation { get; set; }

    [ForeignKey("tipoSalida")]
    [InverseProperty("configuracionProcesotipoSalidaNavigation")]
    public virtual tipoComponente tipoSalidaNavigation { get; set; }
}