// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEntregaPt", Name = "ENTREGA_CONTENIDO_FK")]
public partial class contenidoEntrega
{
    [Key]
    public int idContenidoEntrega { get; set; }

    public int? idEntregaPt { get; set; }

    public int? numeroFila { get; set; }

    public int? cantidadPlanificada { get; set; }

    public int? cantidadEntregada { get; set; }

    [StringLength(254)]
    public string producto { get; set; }

    public string descripcion { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string codigoProducto { get; set; }

    [ForeignKey("idEntregaPt")]
    [InverseProperty("contenidoEntrega")]
    public virtual entregasProductoTerminado idEntregaPtNavigation { get; set; }
}