// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("maestro", Name = "MAESTRO_FK")]
[Index("subordinado", Name = "SUBORDINADO_FK", IsUnique = true)]
public partial class corridaCombinada
{
    [Key]
    public int idRelacion { get; set; }

    public int? maestro { get; set; }

    public int? subordinado { get; set; }

    [ForeignKey("maestro")]
    [InverseProperty("corridaCombinadamaestroNavigation")]
    public virtual procesoOf maestroNavigation { get; set; }

    [ForeignKey("subordinado")]
    [InverseProperty("corridaCombinadasubordinadoNavigation")]
    public virtual procesoOf subordinadoNavigation { get; set; }
}