// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class detalleValidacionArranque
{
    [Key]
    public int idDetalleValidacion { get; set; }

    public int idValidacionArranque { get; set; }

    [StringLength(40)]
    public string colores { get; set; }

    [Column(TypeName = "numeric(12, 2)")]
    public decimal? densidad { get; set; }

    [Column(TypeName = "numeric(12, 2)")]
    public decimal? porcentajeAgua { get; set; }

    [ForeignKey("idValidacionArranque")]
    [InverseProperty("detalleValidacionArranque")]
    public virtual validacionArranque idValidacionArranqueNavigation { get; set; }
}