// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFichaTecnica", Name = "FICHA_TROQUELADO_FK")]
public partial class detalleTroquelado
{
    [Key]
    public int idDetalleTroquelado { get; set; }

    public int? idFichaTecnica { get; set; }

    [StringLength(50)]
    public string anchoSinArmar { get; set; }

    [StringLength(50)]
    public string largoSinArmar { get; set; }

    [StringLength(50)]
    public string anchoArmada { get; set; }

    [StringLength(50)]
    public string largoArmada { get; set; }

    [StringLength(50)]
    public string altoArmada { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadMaquina { get; set; }

    [StringLength(50)]
    public string maquina { get; set; }

    [StringLength(50)]
    public string operario { get; set; }

    [StringLength(50)]
    public string presionMaquina { get; set; }

    [StringLength(50)]
    public string codigoTroquel { get; set; }

    [StringLength(50)]
    public string tipoMatriz { get; set; }

    public int? repeticionesPorTroquel { get; set; }

    public string observaciones { get; set; }

    [ForeignKey("idFichaTecnica")]
    [InverseProperty("detalleTroquelado")]
    public virtual fichaTecnica idFichaTecnicaNavigation { get; set; }

    [InverseProperty("idDetalleTroqueladoNavigation")]
    public virtual ICollection<tipoAcabado> tipoAcabado { get; set; } = new List<tipoAcabado>();

    [InverseProperty("idDetalleTroqueladoNavigation")]
    public virtual ICollection<tipoPleca> tipoPleca { get; set; } = new List<tipoPleca>();
}