// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFichaTecnica", Name = "FICHA_PEGADO_FK")]
public partial class detallePegado
{
    [Key]
    public int idDetallePegado { get; set; }

    public int? idFichaTecnica { get; set; }

    [StringLength(50)]
    public string maquina { get; set; }

    [StringLength(50)]
    public string operario { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadMaquina { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? presionBandaColectora { get; set; }

    [StringLength(50)]
    public string pegaDisco { get; set; }

    [StringLength(50)]
    public string pegaPistola { get; set; }

    public int? bandasATransferir { get; set; }

    [StringLength(50)]
    public string velocidadPegado { get; set; }

    [StringLength(50)]
    public string tipoAcetato { get; set; }

    [StringLength(50)]
    public string espesorAcetato { get; set; }

    [StringLength(50)]
    public string anchoAcetato { get; set; }

    [StringLength(50)]
    public string largoAcetato { get; set; }

    [StringLength(50)]
    public string toleranciaAcetato { get; set; }

    [StringLength(50)]
    public string anchoPega { get; set; }

    [StringLength(50)]
    public string largoPega { get; set; }

    [StringLength(50)]
    public string toleranciaPega { get; set; }

    [StringLength(50)]
    public string alimentacion { get; set; }

    [StringLength(50)]
    public string tipoCorrugado { get; set; }

    public int? unidadesCorrugado { get; set; }

    public bool? fajado { get; set; }

    public int? unidadesFajadas { get; set; }

    public string observaciones { get; set; }

    [ForeignKey("idFichaTecnica")]
    [InverseProperty("detallePegado")]
    public virtual fichaTecnica idFichaTecnicaNavigation { get; set; }

    [InverseProperty("idDetallePegadoNavigation")]
    public virtual ICollection<tipoPega> tipoPega { get; set; } = new List<tipoPega>();

    [InverseProperty("idDetallePegadoNavigation")]
    public virtual ICollection<tipoPegado> tipoPegado { get; set; } = new List<tipoPegado>();
}