// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCondicionInicial", Name = "IDX_CID_CONDICION")]
[Index("idVariable", Name = "IDX_CID_VARIABLE")]
[Index("idCondicionInicial", "idVariable", Name = "UQ_DetalleCondicion", IsUnique = true)]
public partial class detalleCondicionInicial
{
    [Key]
    public int idDetalleCondicionInicial { get; set; }

    public int idCondicionInicial { get; set; }

    public int idVariable { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public string valor { get; set; }

    [StringLength(75)]
    public string valorObjetivo { get; set; }

    [StringLength(75)]
    public string valorMaximo { get; set; }

    [StringLength(75)]
    public string valorMinimo { get; set; }

    public int? idUnidad { get; set; }

    [StringLength(75)]
    public string tolerancia { get; set; }

    public bool? dentroDeRango { get; set; }

    [StringLength(250)]
    public string observaciones { get; set; }

    [ForeignKey("idCondicionInicial")]
    [InverseProperty("detalleCondicionInicial")]
    public virtual condicionInicial idCondicionInicialNavigation { get; set; }

    [ForeignKey("idUnidad")]
    [InverseProperty("detalleCondicionInicial")]
    public virtual unidadesMedida idUnidadNavigation { get; set; }

    [ForeignKey("idVariable")]
    [InverseProperty("detalleCondicionInicial")]
    public virtual variablesTecnicas idVariableNavigation { get; set; }
}