// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetalleImpresion", Name = "FICHA_BARNIZ_FK")]
public partial class detalleBarniz
{
    [Key]
    public int idBarniz { get; set; }

    public int? idDetalleImpresion { get; set; }

    [StringLength(20)]
    public string tipoBarniz { get; set; }

    [StringLength(100)]
    public string nombreBarniz { get; set; }

    [StringLength(50)]
    public string brillo { get; set; }

    [StringLength(50)]
    public string gradoMedicion { get; set; }

    [StringLength(50)]
    public string numeroLote { get; set; }

    [StringLength(50)]
    public string vence { get; set; }

    [StringLength(50)]
    public string viscosidad { get; set; }

    [StringLength(50)]
    public string maquinaBarniz { get; set; }

    [StringLength(50)]
    public string operario { get; set; }

    [StringLength(50)]
    public string lote { get; set; }

    public bool? tipoRegistroPegue { get; set; }

    public bool? tipoRegistroLote { get; set; }

    public bool? tipoRegistroTotal { get; set; }

    public bool? tipoRegistroSinBuv { get; set; }

    [StringLength(50)]
    public string tolerancia { get; set; }

    [ForeignKey("idDetalleImpresion")]
    [InverseProperty("detalleBarniz")]
    public virtual detalleImpresion idDetalleImpresionNavigation { get; set; }

    [InverseProperty("idBarnizNavigation")]
    public virtual ICollection<potenciaLamparaUv> potenciaLamparaUv { get; set; } = new List<potenciaLamparaUv>();
}