// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTipoCierre", Name = "DETALLE_TIPO_CIERRE_FK")]
[Index("maquina", Name = "MAQUINA_FK")]
[Index("idMaterial", Name = "MATERIAL_DETALLE_FK")]
[Index("oF", Name = "OF_DETALLE_REPORTE_FK")]
[Index("idOperacion", Name = "OPERACION_DETALLE_FK")]
[Index("idProceso", Name = "PROCESO_REPORTE_FK")]
[Index("idReporte", Name = "REPORTE_DETALLE_FK")]
public partial class detalleReporte
{
    [Key]
    public int idDetalleReporte { get; set; }

    [StringLength(50)]
    public string idReporte { get; set; }

    public int? idOperacion { get; set; }

    [StringLength(25)]
    public string idMaterial { get; set; }

    public int? idProceso { get; set; }

    public int? idTipoCierre { get; set; }

    public int? oF { get; set; }

    public int? numeroFila { get; set; }

    public TimeOnly? horaInicio { get; set; }

    public TimeOnly? horaFinal { get; set; }

    public TimeOnly? tiempo { get; set; }

    public string descripcion { get; set; }

    [StringLength(200)]
    public string cliente { get; set; }

    [StringLength(1)]
    public string tiroRetiro { get; set; }

    public int? cantidadRecibida { get; set; }

    public int? cantidadProducida { get; set; }

    public int? cantidadDanada { get; set; }

    public int? cantidadSolicitada { get; set; }

    public int? cantProducida { get; set; }

    public int? cantidadAjuste { get; set; }

    public int? cantidadNc { get; set; }

    public int? cantProducir { get; set; }

    public int? cantidadMtEnRollos { get; set; }

    public int? cantidadEnRollos { get; set; }

    public int? anchoBobina { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadMaquina { get; set; }

    public string observaciones { get; set; }

    public int? largoConvertido { get; set; }

    public int? bjAncho { get; set; }

    public int? bjLargo { get; set; }

    public int? bsAncho { get; set; }

    public int? bsLargo { get; set; }

    public int? ancho { get; set; }

    public int? alto { get; set; }

    public int? repeticiones { get; set; }

    public int? cantidadSobrante { get; set; }

    public int? udCorrugados { get; set; }

    public bool? accionPorAuxiliar { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaHora { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public int? numAuxiliares { get; set; }

    public int? maquina { get; set; }

    public DateOnly? fecha { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [ForeignKey("idMaterial")]
    [InverseProperty("detalleReporte")]
    public virtual material idMaterialNavigation { get; set; }

    [ForeignKey("idOperacion")]
    [InverseProperty("detalleReporte")]
    public virtual operaciones idOperacionNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("detalleReporte")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("idReporte")]
    [InverseProperty("detalleReporte")]
    public virtual reportesDeOperadores idReporteNavigation { get; set; }

    [ForeignKey("idTipoCierre")]
    [InverseProperty("detalleReporte")]
    public virtual tipoCierre idTipoCierreNavigation { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("detalleReporte")]
    public virtual maquinas maquinaNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("detalleReporte")]
    public virtual tarjetaOf oFNavigation { get; set; }
}