// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class detalleGira
{
    [Key]
    public int idDetalleGira { get; set; }

    public int? idGira { get; set; }

    [StringLength(300)]
    public string resumen { get; set; }

    public int? factura { get; set; }

    public int? idTarjetaOf { get; set; }

    [ForeignKey("idGira")]
    [InverseProperty("detalleGira")]
    public virtual gira idGiraNavigation { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("detalleGira")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}