// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFichaTecnica", Name = "FICHA_DETALLE_FK")]
public partial class detalleFicha
{
    [Key]
    public int idDetalleFicha { get; set; }

    public int? idFichaTecnica { get; set; }

    [ForeignKey("idFichaTecnica")]
    [InverseProperty("detalleFicha")]
    public virtual fichaTecnica idFichaTecnicaNavigation { get; set; }
}