// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTipoCierre", Name = "DETALLE_TIPO_CIERRE_FK")]
[Index("idMaterial", Name = "MATERIAL_DETALLE_FK")]
[Index("idOperacion", Name = "OPERACION_DETALLE_FK")]
[Index("idReporte", Name = "REPORTE_DETALLE_FK")]
[Index("idTarjetaOf", Name = "TARJETA_DETALLE_REPORTE_FK")]
public partial class detalleReporte
{
    [Key]
    public int idDetalle { get; set; }

    public int? idReporte { get; set; }

    public int? idOperacion { get; set; }

    public int? idMaterial { get; set; }

    public int? idTarjetaOf { get; set; }

    public int? idTipoCierre { get; set; }

    public int? numeroFila { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? horaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? horaFinal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? tiempo { get; set; }

    public string descripcion { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string cliente { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string tiroRetiro { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadRecibida { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadProducida { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadDanada { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadSolicitada { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadProducidaMt { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadAjuste { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? anchoBobina { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? velocidadMaquina { get; set; }

    public string observaciones { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? largoConvertido { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? anchoMm { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? largoMm { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? anchoMt { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? largoMt { get; set; }

    public int? repeticiones { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? cantidadSobrante { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? alto { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? udCorrugados { get; set; }

    [ForeignKey("idMaterial")]
    [InverseProperty("detalleReporte")]
    public virtual material idMaterialNavigation { get; set; }

    [ForeignKey("idOperacion")]
    [InverseProperty("detalleReporte")]
    public virtual operaciones idOperacionNavigation { get; set; }

    [ForeignKey("idReporte")]
    [InverseProperty("detalleReporte")]
    public virtual reportesDeOperadores idReporteNavigation { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("detalleReporte")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }

    [ForeignKey("idTipoCierre")]
    [InverseProperty("detalleReporte")]
    public virtual tipoCierre idTipoCierreNavigation { get; set; }
}