// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEntregaPt", Name = "ENTREGA_DETALLE_FK")]
public partial class detalleEntrega
{
    [Key]
    public int idDetalleEntrega { get; set; }

    public int? idEntregaPt { get; set; }

    public int? numeroFila { get; set; }

    public int? cantidadBultos { get; set; }

    [StringLength(200)]
    public string descripcionBultos { get; set; }

    [StringLength(100)]
    public string pesoBultos { get; set; }

    [ForeignKey("idEntregaPt")]
    [InverseProperty("detalleEntrega")]
    public virtual entregasProductoTerminado idEntregaPtNavigation { get; set; }
}