// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFichaTecnica", Name = "FICHA_IMPRESION_FK")]
public partial class detalleImpresion
{
    [Key]
    public int idDetalleImpresion { get; set; }

    public int? idFichaTecnica { get; set; }

    [StringLength(50)]
    public string maquina { get; set; }

    [StringLength(50)]
    public string operario { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadMaquina { get; set; }

    [StringLength(150)]
    public string resolucionPlancha { get; set; }

    [StringLength(150)]
    public string familiaTramadoPlancha { get; set; }

    [StringLength(50)]
    public string formaPunto { get; set; }

    [StringLength(150)]
    public string lineaturaPlancha { get; set; }

    [StringLength(150)]
    public string curvasPlancha { get; set; }

    [StringLength(150)]
    public string tipoPlancha { get; set; }

    [StringLength(150)]
    public string colorTiro { get; set; }

    [StringLength(150)]
    public string colorRetiro { get; set; }

    [StringLength(150)]
    public string proveedorTintas { get; set; }

    [StringLength(50)]
    public string presionGeneralMaquina { get; set; }

    [StringLength(50)]
    public string porcentajeTalco { get; set; }

    [StringLength(50)]
    public string tipoTalco { get; set; }

    [StringLength(50)]
    public string temperaturaSalida { get; set; }

    public bool? automatico { get; set; }

    [StringLength(50)]
    public string phAgua { get; set; }

    [StringLength(50)]
    public string conductividadAgua { get; set; }

    [StringLength(50)]
    public string alcoholAgua { get; set; }

    [StringLength(50)]
    public string temperaturaAgua { get; set; }

    public string observaciones { get; set; }

    [StringLength(100)]
    public string formuladoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFormulado { get; set; }

    [StringLength(50)]
    public string datoInstrumento { get; set; }

    public bool? calibracionPapel { get; set; }

    [InverseProperty("idDetalleImpresionNavigation")]
    public virtual ICollection<detalleBarniz> detalleBarniz { get; set; } = new List<detalleBarniz>();

    [InverseProperty("idDetalleImpresionNavigation")]
    public virtual ICollection<detalleSecado> detalleSecado { get; set; } = new List<detalleSecado>();

    [InverseProperty("idDetalleImpresionNavigation")]
    public virtual ICollection<filtros> filtros { get; set; } = new List<filtros>();

    [InverseProperty("idDetalleImpresionNavigation")]
    public virtual ICollection<formulacionTintas> formulacionTintas { get; set; } = new List<formulacionTintas>();

    [ForeignKey("idFichaTecnica")]
    [InverseProperty("detalleImpresion")]
    public virtual fichaTecnica idFichaTecnicaNavigation { get; set; }

    [InverseProperty("idDetalleImpresionNavigation")]
    public virtual ICollection<secuenciaDeColor> secuenciaDeColor { get; set; } = new List<secuenciaDeColor>();
}