// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("maquina", Name = "MAQUINA_FK")]
[Index("idProceso", Name = "PROCESO_OPERACIONES_FK")]
[Index("idOperacion", Name = "TIPO_OPERACION_FK")]
public partial class detalleOperacionProceso
{
    [Key]
    public int idDetalleOperacion { get; set; }

    public int? idProceso { get; set; }

    public int? idOperacion { get; set; }

    public int? numeroFila { get; set; }

    public int? secuencia { get; set; }

    public TimeOnly? inicio { get; set; }

    public TimeOnly? finalizacion { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public int? operacion { get; set; }

    public bool? accionPorAuxiliar { get; set; }

    [StringLength(50)]
    public string auxiliar { get; set; }

    public int? cantidadRecibida { get; set; }

    public int? cantidadProducida { get; set; }

    public int? cantidadNc { get; set; }

    public int? idDetalleReporte { get; set; }

    [StringLength(1)]
    public string tiroRetiro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaHora { get; set; }

    public int? bjAncho { get; set; }

    public int? bjLargo { get; set; }

    public int? largoConvertido { get; set; }

    public int? bsLargo { get; set; }

    public int? bsAncho { get; set; }

    public int? anchoBobina { get; set; }

    public int? cantAjuste { get; set; }

    public int? cantProducir { get; set; }

    public int? cantSolicitada { get; set; }

    public int? cantProducida { get; set; }

    public int? maquina { get; set; }

    public int? numAuxiliares { get; set; }

    [ForeignKey("idOperacion")]
    [InverseProperty("detalleOperacionProceso")]
    public virtual operaciones idOperacionNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("detalleOperacionProceso")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("detalleOperacionProceso")]
    public virtual maquinas maquinaNavigation { get; set; }
}