// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCertificado", Name = "DETALLE_CERTIFICADO_FK")]
[Index("idCaracterista", Name = "ESPECIFICACION_FK")]
public partial class detalleCertificado
{
    [Key]
    public int idDetalleCertificado { get; set; }

    public int? idCertificado { get; set; }

    public int? idCaracterista { get; set; }

    public int? numeroFila { get; set; }

    [StringLength(250)]
    public string especificacion { get; set; }

    [StringLength(10)]
    public string resultado { get; set; }

    [ForeignKey("idCaracterista")]
    [InverseProperty("detalleCertificado")]
    public virtual especificaciones idCaracteristaNavigation { get; set; }

    [ForeignKey("idCertificado")]
    [InverseProperty("detalleCertificado")]
    public virtual certificadoDeCalidad idCertificadoNavigation { get; set; }
}