// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCertificado", Name = "CERTIFICADO_DETALLE_FK")]
public partial class detalleCertificado
{
    [Key]
    public int idDetalleCertificado { get; set; }

    public int? idCertificado { get; set; }

    [ForeignKey("idCertificado")]
    [InverseProperty("detalleCertificado")]
    public virtual certificadoDeCalidad idCertificadoNavigation { get; set; }
}