// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class detalleCertificadoCalidad_Log
{
    [Key]
    public int idLogDetalle { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaLog { get; set; }

    [StringLength(50)]
    public string usuarioLog { get; set; }

    [StringLength(10)]
    public string tipoAccion { get; set; }

    public int idDetalle { get; set; }

    public int idCertificadoCalidad { get; set; }

    public int idVariable { get; set; }

    public string valor { get; set; }

    [StringLength(75)]
    public string resultado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public int? idUnidad { get; set; }

    [StringLength(75)]
    public string toleranciaMedida { get; set; }
}