// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class detalleAuditoriaProceso
{
    [Key]
    public int idDetalle { get; set; }

    public int? idAuditoria { get; set; }

    public int? idVariable { get; set; }

    [StringLength(10)]
    public string valor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [ForeignKey("idAuditoria")]
    [InverseProperty("detalleAuditoriaProceso")]
    public virtual auditoriaProceso idAuditoriaNavigation { get; set; }

    [ForeignKey("idVariable")]
    [InverseProperty("detalleAuditoriaProceso")]
    public virtual variablesTecnicas idVariableNavigation { get; set; }
}