// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEntregaPt", Name = "ENTREGA_DETALLE_FK")]
[Index("numeroOF", Name = "NUMERO_OF_FK")]
public partial class detalleEntrega
{
    [Key]
    public int idDetalleEntrega { get; set; }

    public int? idEntregaPt { get; set; }

    public int? numeroFila { get; set; }

    public int? numeroOF { get; set; }

    [StringLength(300)]
    public string cliente { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? cantidad { get; set; }

    [StringLength(50)]
    public string codArticuloSAP { get; set; }

    [StringLength(50)]
    public string tipoEmpaque { get; set; }

    public int? bultos { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? peso { get; set; }

    [StringLength(300)]
    public string nombreArticulo { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? cantidadTotal { get; set; }

    [ForeignKey("idEntregaPt")]
    [InverseProperty("detalleEntrega")]
    public virtual entregasProductoTerminado idEntregaPtNavigation { get; set; }

    [ForeignKey("numeroOF")]
    [InverseProperty("detalleEntrega")]
    public virtual tarjetaOf numeroOFNavigation { get; set; }
}