// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class detalleFichaProcesos
{
    [Key]
    public int idDetalle { get; set; }

    public int? idFichaProceso { get; set; }

    public int? idVariable { get; set; }

    public string valor { get; set; }

    public int? idUnidad { get; set; }

    public string toleranciaMedida { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCracion { get; set; }

    [ForeignKey("idFichaProceso")]
    [InverseProperty("detalleFichaProcesos")]
    public virtual fichaTecnicaProcesos idFichaProcesoNavigation { get; set; }

    [ForeignKey("idUnidad")]
    [InverseProperty("detalleFichaProcesos")]
    public virtual unidadesMedida idUnidadNavigation { get; set; }

    [ForeignKey("idVariable")]
    [InverseProperty("detalleFichaProcesos")]
    public virtual variablesTecnicas idVariableNavigation { get; set; }
}