// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class dictamenCalidad
{
    [Key]
    public int idDictamen { get; set; }

    [Required]
    [StringLength(60)]
    public string nombre { get; set; }

    [StringLength(200)]
    public string descripcion { get; set; }

    public bool aplicaPreliminar { get; set; }

    public bool aplicaFinal { get; set; }

    public int? ideEstadoSugerido { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idDictamenNavigation")]
    public virtual ICollection<bitacoraCaso> bitacoraCaso { get; set; } = new List<bitacoraCaso>();
}