// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("user", Name = "USUARIO_DISENADOR_FK")]
public partial class disenador
{
    [Key]
    public int idDisenador { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string user { get; set; }

    [StringLength(200)]
    public string nombreDisenador { get; set; }

    [StringLength(250)]
    public string cargoDisenador { get; set; }

    [InverseProperty("idDisenadorNavigation")]
    public virtual ICollection<asignacion> asignacion { get; set; } = new List<asignacion>();

    [ForeignKey("user")]
    [InverseProperty("disenador")]
    public virtual usuario userNavigation { get; set; }
}