// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class empleadoCatalogo
{
    [Key]
    public int idEmpleado { get; set; }

    [StringLength(100)]
    public string nombres { get; set; }

    [StringLength(100)]
    public string apellidos { get; set; }
}