// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEstadoReporte", Name = "ESTADO_ENTREGA_FK")]
[Index("idMaquina", Name = "MAQUINA_ENTREGA_FK")]
[Index("idOv", Name = "OV_ENTREGA_FK")]
[Index("idTarjetaOf", Name = "TARJETA_ENTREGA_FK")]
public partial class entregasProductoTerminado
{
    [Key]
    public int idEntregaPt { get; set; }

    public int? idTarjetaOf { get; set; }

    public int? idMaquina { get; set; }

    public int? idOv { get; set; }

    public int? idEstadoReporte { get; set; }

    public int? numeroOf { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string cliente { get; set; }

    public string descripcionOf { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaEntrega { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string areaEntrega { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string areaRecibe { get; set; }

    public int? numeroDeCorrugados { get; set; }

    public int? numeroDeTarimas { get; set; }

    public int? numeroDeEntrega { get; set; }

    [StringLength(100)]
    public string creadoPor { get; set; }

    [StringLength(100)]
    public string recibidoPor { get; set; }

    public bool? entregaParcial { get; set; }

    public bool? reportaSobrantes { get; set; }

    public int? cantidadSobrante { get; set; }

    public int? cantidadEntregadaTotal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string actualizadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ultimaActualizacion { get; set; }

    public int? tipoObjeto { get; set; }

    [InverseProperty("idEntregaPtNavigation")]
    public virtual ICollection<contenidoEntrega> contenidoEntrega { get; set; } = new List<contenidoEntrega>();

    [InverseProperty("idEntregaPtNavigation")]
    public virtual ICollection<detalleEntrega> detalleEntrega { get; set; } = new List<detalleEntrega>();

    [ForeignKey("idEstadoReporte")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual estadosReporte idEstadoReporteNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual maquinas idMaquinaNavigation { get; set; }

    [ForeignKey("idOv")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual oV idOvNavigation { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}