// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEstadoReporte", Name = "ESTADO_ENTREGA_FK")]
[Index("idMaquina", Name = "MAQUINA_ENTREGA_FK")]
[Index("of", Name = "OF_ENTREGA_FK")]
public partial class entregasProductoTerminado
{
    [Key]
    public int idEntregaPt { get; set; }

    public int? idMaquina { get; set; }

    public int? idEstadoReporte { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaEntrega { get; set; }

    [StringLength(100)]
    public string areaEntrega { get; set; }

    [StringLength(100)]
    public string areaRecibe { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaRecepcion { get; set; }

    public int? numeroDeTarimas { get; set; }

    public int? numeroDeCorrugados { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    [StringLength(100)]
    public string recibidoPor { get; set; }

    public bool? entregaParcial { get; set; }

    public bool? reportaSobrantes { get; set; }

    public int? cantidadSobrante { get; set; }

    public int? cantidadEntregadaTotal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ultimaActualizacion { get; set; }

    public int? tipoObjeto { get; set; }

    [StringLength(100)]
    public string entregadoPor { get; set; }

    public int? of { get; set; }

    [InverseProperty("idEntregaPtNavigation")]
    public virtual ICollection<contenidoEntrega> contenidoEntrega { get; set; } = new List<contenidoEntrega>();

    [InverseProperty("idEntregaPtNavigation")]
    public virtual ICollection<detalleEntrega> detalleEntrega { get; set; } = new List<detalleEntrega>();

    [ForeignKey("idEstadoReporte")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual estadosReporte idEstadoReporteNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual maquinas idMaquinaNavigation { get; set; }

    [ForeignKey("of")]
    [InverseProperty("entregasProductoTerminado")]
    public virtual tarjetaOf ofNavigation { get; set; }
}