// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class especificacionTintas
{
    [Key]
    public int idEspecificacion { get; set; }

    public int? idFormulacion { get; set; }

    [StringLength(100)]
    public string descripcion { get; set; }

    [StringLength(250)]
    public string proveedor { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? porcentajeTinta { get; set; }

    [StringLength(100)]
    public string loteTinta { get; set; }

    [ForeignKey("idFormulacion")]
    [InverseProperty("especificacionTintas")]
    public virtual formulacionTinta idFormulacionNavigation { get; set; }
}