// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("tipoReporte", Name = "TIPO_REPORTE_FK")]
public partial class estadosReporte
{
    [Key]
    public int idEstadoReporte { get; set; }

    [StringLength(100)]
    public string nombreEstado { get; set; }

    public int? tipoReporte { get; set; }

    [InverseProperty("estadoNavigation")]
    public virtual ICollection<auditoriaProceso> auditoriaProceso { get; set; } = new List<auditoriaProceso>();

    [InverseProperty("estadoAnteriorNavigation")]
    public virtual ICollection<bitacoraCaso> bitacoraCasoestadoAnteriorNavigation { get; set; } = new List<bitacoraCaso>();

    [InverseProperty("estadoNuevoNavigation")]
    public virtual ICollection<bitacoraCaso> bitacoraCasoestadoNuevoNavigation { get; set; } = new List<bitacoraCaso>();

    [InverseProperty("idEstadoNavigation")]
    public virtual ICollection<casoAccionSolicitada> casoAccionSolicitada { get; set; } = new List<casoAccionSolicitada>();

    [InverseProperty("idEstadoNavigation")]
    public virtual ICollection<casoCalidad> casoCalidad { get; set; } = new List<casoCalidad>();

    [InverseProperty("idEstadoNavigation")]
    public virtual ICollection<confirmacionPreliminar> confirmacionPreliminar { get; set; } = new List<confirmacionPreliminar>();

    [InverseProperty("idEstadoReporteNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [InverseProperty("estadoNavigation")]
    public virtual ICollection<fichaTecnicaProcesos> fichaTecnicaProcesos { get; set; } = new List<fichaTecnicaProcesos>();

    [InverseProperty("idEstadoReporteNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();

    [ForeignKey("tipoReporte")]
    [InverseProperty("estadosReporte")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }

    [InverseProperty("estadoNavigation")]
    public virtual ICollection<turnoAuditoria> turnoAuditoria { get; set; } = new List<turnoAuditoria>();

    [InverseProperty("estadoNavigation")]
    public virtual ICollection<valeBobina> valeBobina { get; set; } = new List<valeBobina>();

    [InverseProperty("estadoNavigation")]
    public virtual ICollection<validacionArranque> validacionArranque { get; set; } = new List<validacionArranque>();
}