// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("tipoReporte", Name = "TIPO_REPORTE_FK")]
public partial class estadosReporte
{
    [Key]
    public int idEstadoReporte { get; set; }

    [StringLength(100)]
    public string nombreEstado { get; set; }

    public int? tipoReporte { get; set; }

    [InverseProperty("idEstadoReporteNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [InverseProperty("idEstadoReporteNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();

    [ForeignKey("tipoReporte")]
    [InverseProperty("estadosReporte")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }
}