// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class etiquetaSolicitud
{
    [Key]
    public int idEtiqSolicitud { get; set; }

    public int? idSolicitud { get; set; }

    public int? idEtiqueta { get; set; }

    [ForeignKey("idEtiqueta")]
    [InverseProperty("etiquetaSolicitud")]
    public virtual etiqueta idEtiquetaNavigation { get; set; }

    [ForeignKey("idSolicitud")]
    [InverseProperty("etiquetaSolicitud")]
    public virtual solicitudMateriales idSolicitudNavigation { get; set; }
}