// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTarjetaOf", Name = "TARJETA_ETIQUETA_FK")]
public partial class etiqueta
{
    [Key]
    public int idEtiqueta { get; set; }

    public int? idTarjetaOf { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string color { get; set; }

    [StringLength(100)]
    public string texto { get; set; }

    public int? secuencia { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("etiqueta")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}