// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class etiqueta
{
    [Key]
    public int idEtiqueta { get; set; }

    [StringLength(100)]
    public string color { get; set; }

    [StringLength(100)]
    public string texto { get; set; }

    public int? secuencia { get; set; }

    public int? flag { get; set; }

    [InverseProperty("idEtiquetaNavigation")]
    public virtual ICollection<etiquetaOf> etiquetaOf { get; set; } = new List<etiquetaOf>();

    [InverseProperty("idEtiquetaNavigation")]
    public virtual ICollection<tarjetaEtiqueta> tarjetaEtiqueta { get; set; } = new List<tarjetaEtiqueta>();
}