// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class FFE_ResumenOFResult
    {
        public int? idOF { get; set; }
        public DateTime? fechaInicioCalculada { get; set; }
        public DateTime? fechaFinEstimada_FFE { get; set; }
        public DateTime? fechaVencimiento { get; set; }
        public int estaAtrasada { get; set; }
        [StringLength(250)]
        public string causaCritica { get; set; }
    }
}
