// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class FFE_DetalleProcesosResult
    {
        public int? idProceso { get; set; }
        public int? secuenciaArea { get; set; }
        [StringLength(100)]
        public string nombrePostura { get; set; }
        [StringLength(200)]
        public string idMaquinaSAP { get; set; }
        [Column("tiempoEstimado", TypeName = "decimal(20,2)")]
        public decimal? tiempoEstimado { get; set; }
        public DateTime? fechaInicioReal { get; set; }
        public DateTime? fechaInicioEstimada { get; set; }
        public DateTime? fechaFinalReal { get; set; }
        public DateTime? fechaFinalEstimada { get; set; }
        [StringLength(20)]
        public string tipoDato { get; set; }
        [StringLength(250)]
        public string causaAtraso { get; set; }
    }
}
