// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class ffeTiemposOfGlobal
{
    [Key]
    public int idOF { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Inicio_Real { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Inicio_Estimado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fin_Real { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fin_Proyectado { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Vencimiento_SAP { get; set; }

    public int? Atrasada { get; set; }

    [StringLength(250)]
    public string Estado_Causa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Actualizado { get; set; }

    [ForeignKey("idOF")]
    [InverseProperty("ffeTiemposOfGlobal")]
    public virtual tarjetaOf idOFNavigation { get; set; }
}