// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFichaCliente", Name = "FK_CERTIFICADO_FICHACLIENTE")]
public partial class fichaTecnicaCliente
{
    [Key]
    public int idFichaCliente { get; set; }

    public int codClienteSAP { get; set; }

    public int codProductoSAP { get; set; }

    [Required]
    [StringLength(50)]
    public string elaboradoPor { get; set; }

    public DateOnly fechaElaboracion { get; set; }

    public string observaciones { get; set; }

    public int? version { get; set; }

    public bool? vigente { get; set; }

    public DateOnly? fechaVencimiento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [InverseProperty("idFichaClienteNavigation")]
    public virtual ICollection<certificadoCalidad> certificadoCalidad { get; set; } = new List<certificadoCalidad>();

    [InverseProperty("idFichaClienteNavigation")]
    public virtual ICollection<detalleFichaClientes> detalleFichaClientes { get; set; } = new List<detalleFichaClientes>();

    [ForeignKey("elaboradoPor")]
    [InverseProperty("fichaTecnicaCliente")]
    public virtual usuario elaboradoPorNavigation { get; set; }

    [InverseProperty("idFichaClienteNavigation")]
    public virtual ICollection<fichaClienteOf> fichaClienteOf { get; set; } = new List<fichaClienteOf>();
}