// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("oF", Name = "OF_FICHA_FK")]
[Index("idTipoFicha", Name = "TIPO_DE_FICHA_FK")]
public partial class fichaTecnica
{
    [Key]
    public int idFichaTecnica { get; set; }

    public int? oF { get; set; }

    public int? idTipoFicha { get; set; }

    [StringLength(200)]
    public string cliente { get; set; }

    [StringLength(100)]
    public string codigoProducto { get; set; }

    [StringLength(254)]
    public string producto { get; set; }

    [StringLength(200)]
    public string tipoDeProducto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFicha { get; set; }

    [StringLength(150)]
    public string tipoMaterial { get; set; }

    [StringLength(100)]
    public string toleranciaMaterial { get; set; }

    [StringLength(100)]
    public string marcarMaterial { get; set; }

    [StringLength(25)]
    public string calibreMaterial { get; set; }

    [StringLength(50)]
    public string proveedorMaterial { get; set; }

    [StringLength(100)]
    public string encargadoCalidad { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCalidad { get; set; }

    public int? tipoObjeto { get; set; }

    [StringLength(100)]
    public string creadoPor { get; set; }

    public int? version { get; set; }

    [InverseProperty("idFichaTecnicaNavigation")]
    public virtual ICollection<detalleImpresion> detalleImpresion { get; set; } = new List<detalleImpresion>();

    [InverseProperty("idFichaTecnicaNavigation")]
    public virtual ICollection<detallePegado> detallePegado { get; set; } = new List<detallePegado>();

    [InverseProperty("idFichaTecnicaNavigation")]
    public virtual ICollection<detalleTroquelado> detalleTroquelado { get; set; } = new List<detalleTroquelado>();

    [ForeignKey("idTipoFicha")]
    [InverseProperty("fichaTecnica")]
    public virtual tipoFicha idTipoFichaNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("fichaTecnica")]
    public virtual tarjetaOf oFNavigation { get; set; }
}