// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTarjetaOf", Name = "TARJETA_FICHA_FK")]
public partial class fichaTecnica
{
    [Key]
    public int idFichaTecnica { get; set; }

    public int? idTarjetaOf { get; set; }

    [StringLength(100)]
    public string creadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFicha { get; set; }

    [StringLength(200)]
    public string cliente { get; set; }

    [StringLength(254)]
    public string producto { get; set; }

    public int? numeroOf { get; set; }

    public int? tipoObjeto { get; set; }

    [InverseProperty("idFichaTecnicaNavigation")]
    public virtual ICollection<detalleFicha> detalleFicha { get; set; } = new List<detalleFicha>();

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("fichaTecnica")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}