// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class fichaTecnicaCliente_Log
{
    [Key]
    public int idLog { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaLog { get; set; }

    [StringLength(50)]
    public string usuarioLog { get; set; }

    [StringLength(10)]
    public string tipoAccion { get; set; }

    public int idFichaCliente { get; set; }

    [Required]
    [StringLength(50)]
    public string codClienteSAP { get; set; }

    [Required]
    [StringLength(50)]
    public string codProductoSAP { get; set; }

    [Required]
    [StringLength(50)]
    public string elaboradoPor { get; set; }

    public DateOnly fechaElaboracion { get; set; }

    public string observaciones { get; set; }

    public int? version { get; set; }

    public bool? vigente { get; set; }

    public DateOnly? fechaVencimiento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public int? oF { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }
}