// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class fichaTecnicaProcesos
{
    [Key]
    public int idFichaProceso { get; set; }

    public int? oF { get; set; }

    public int? idProceso { get; set; }

    public int? maquina { get; set; }

    public int? estado { get; set; }

    public int? tipoProceso { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public string observaciones { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? presionGeneral { get; set; }

    public int? version { get; set; }

    public bool? vigente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    public DateOnly? fechaFormulacion { get; set; }

    [StringLength(50)]
    public string formuladorTinta { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    public int? tipoReporte { get; set; }

    public bool? archivado { get; set; }

    public bool? cancelado { get; set; }

    [ForeignKey("actualizadoPor")]
    [InverseProperty("fichaTecnicaProcesosactualizadoPorNavigation")]
    public virtual usuario actualizadoPorNavigation { get; set; }

    [ForeignKey("creadoPor")]
    [InverseProperty("fichaTecnicaProcesoscreadoPorNavigation")]
    public virtual usuario creadoPorNavigation { get; set; }

    [InverseProperty("idFichaProcesoNavigation")]
    public virtual ICollection<detalleFichaProcesos> detalleFichaProcesos { get; set; } = new List<detalleFichaProcesos>();

    [ForeignKey("estado")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual estadosReporte estadoNavigation { get; set; }

    [InverseProperty("idFichaProcesoNavigation")]
    public virtual ICollection<formulacionTinta> formulacionTinta { get; set; } = new List<formulacionTinta>();

    [ForeignKey("formuladorTinta")]
    [InverseProperty("fichaTecnicaProcesosformuladorTintaNavigation")]
    public virtual usuario formuladorTintaNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual procesoOf idProcesoNavigation { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual maquinas maquinaNavigation { get; set; }

    [InverseProperty("idFichaProcesoNavigation")]
    public virtual ICollection<medicionAguas> medicionAguas { get; set; } = new List<medicionAguas>();

    [ForeignKey("oF")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("fichaTecnicaProcesosoperadorNavigation")]
    public virtual usuario operadorNavigation { get; set; }

    [InverseProperty("idFichaProcesoNavigation")]
    public virtual ICollection<registroLamparas> registroLamparas { get; set; } = new List<registroLamparas>();

    [InverseProperty("idFichaProcesoNavigation")]
    public virtual ICollection<secuenciaColor> secuenciaColor { get; set; } = new List<secuenciaColor>();

    [ForeignKey("tipoProceso")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual areas tipoProcesoNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("fichaTecnicaProcesos")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }
}