// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[PrimaryKey("idFlag", "tipoDocumento")]
public partial class flagTipoDocumento
{
    [Key]
    public int idFlag { get; set; }

    [Key]
    public int tipoDocumento { get; set; }

    public int orden { get; set; }

    [ForeignKey("idFlag")]
    [InverseProperty("flagTipoDocumento")]
    public virtual catalogoFlag idFlagNavigation { get; set; }

    [ForeignKey("tipoDocumento")]
    [InverseProperty("flagTipoDocumento")]
    public virtual tipoReporte tipoDocumentoNavigation { get; set; }
}