// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("tipoDocumento", "idDocumento", "activa", Name = "flagDocumento_documento_IX")]
[Index("idFlag", "activa", Name = "flagDocumento_idFlag_IX")]
public partial class flagDocumento
{
    [Key]
    public int idFlagDocumento { get; set; }

    public int idFlag { get; set; }

    public int tipoDocumento { get; set; }

    public int idDocumento { get; set; }

    [StringLength(500)]
    public string texto { get; set; }

    public bool activa { get; set; }

    public int? idFlagOrigen { get; set; }

    public int? idFlagRaiz { get; set; }

    [StringLength(40)]
    public string eventoRegistro { get; set; }

    [StringLength(50)]
    public string registradoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaRegistro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaRemocion { get; set; }

    [StringLength(40)]
    public string eventoRemocion { get; set; }

    [StringLength(50)]
    public string removidoPor { get; set; }

    [StringLength(500)]
    public string motivoRemocion { get; set; }

    [InverseProperty("idFlagOrigenNavigation")]
    public virtual ICollection<flagDocumento> InverseidFlagOrigenNavigation { get; set; } = new List<flagDocumento>();

    [InverseProperty("idFlagRaizNavigation")]
    public virtual ICollection<flagDocumento> InverseidFlagRaizNavigation { get; set; } = new List<flagDocumento>();

    [ForeignKey("idFlag")]
    [InverseProperty("flagDocumento")]
    public virtual catalogoFlag idFlagNavigation { get; set; }

    [ForeignKey("idFlagOrigen")]
    [InverseProperty("InverseidFlagOrigenNavigation")]
    public virtual flagDocumento idFlagOrigenNavigation { get; set; }

    [ForeignKey("idFlagRaiz")]
    [InverseProperty("InverseidFlagRaizNavigation")]
    public virtual flagDocumento idFlagRaizNavigation { get; set; }

    [ForeignKey("registradoPor")]
    [InverseProperty("flagDocumentoregistradoPorNavigation")]
    public virtual usuario registradoPorNavigation { get; set; }

    [ForeignKey("removidoPor")]
    [InverseProperty("flagDocumentoremovidoPorNavigation")]
    public virtual usuario removidoPorNavigation { get; set; }

    [ForeignKey("tipoDocumento")]
    [InverseProperty("flagDocumento")]
    public virtual tipoReporte tipoDocumentoNavigation { get; set; }
}