// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class formulacionTinta
{
    [Key]
    public int idFormulacion { get; set; }

    public int? idFichaProceso { get; set; }

    [StringLength(50)]
    public string color { get; set; }

    [StringLength(50)]
    public string referencia { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? cie_L { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? cie_a { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? cie_b { get; set; }

    [InverseProperty("idFormulacionNavigation")]
    public virtual ICollection<especificacionTintas> especificacionTintas { get; set; } = new List<especificacionTintas>();

    [ForeignKey("idFichaProceso")]
    [InverseProperty("formulacionTinta")]
    public virtual fichaTecnicaProcesos idFichaProcesoNavigation { get; set; }
}