// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEspacioColor", Name = "COLOR_TINTA_FK")]
public partial class generalidadColor
{
    [Key]
    public int idGeneralidad { get; set; }

    public int? idEspacioColor { get; set; }

    [StringLength(50)]
    public string descripcionTinta { get; set; }

    [StringLength(50)]
    public string proveedorTinta { get; set; }

    [StringLength(50)]
    public string porcentajeTinta { get; set; }

    [ForeignKey("idEspacioColor")]
    [InverseProperty("generalidadColor")]
    public virtual espacioColor idEspacioColorNavigation { get; set; }
}