// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class gira
{
    [Key]
    public int idGira { get; set; }

    public int? idMotorista { get; set; }

    public int? idVehiculo { get; set; }

    [StringLength(200)]
    public string resumen { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha { get; set; }

    [InverseProperty("idGiraNavigation")]
    public virtual ICollection<detalleGira> detalleGira { get; set; } = new List<detalleGira>();

    [ForeignKey("idMotorista")]
    [InverseProperty("gira")]
    public virtual motorista idMotoristaNavigation { get; set; }

    [ForeignKey("idVehiculo")]
    [InverseProperty("gira")]
    public virtual vehiculo idVehiculoNavigation { get; set; }
}