// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class horariosOperativos
{
    [Key]
    public int idHorario { get; set; }

    public int? idArea { get; set; }

    public int? idMaquina { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public DateOnly? fecha { get; set; }

    public TimeOnly? horaInicio { get; set; }

    public TimeOnly? horaFin { get; set; }

    [StringLength(50)]
    public string estado { get; set; }

    [StringLength(999)]
    public string operadoresAdicionales { get; set; }

    [ForeignKey("idArea")]
    [InverseProperty("horariosOperativos")]
    public virtual areas idAreaNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("horariosOperativos")]
    public virtual maquinas idMaquinaNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("horariosOperativos")]
    public virtual usuario operadorNavigation { get; set; }
}