// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Sistema_Produccion_3_Backend.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial interface Ibase_nuevaContextProcedures
    {
        Task<List<IndicadoresReporteResult>> IndicadoresReporteAsync(string idReporte, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TimeInListResult>> TimeInListAsync(int? idProceso, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
