// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class IndicadoresReporteResult
    {
        [StringLength(30)]
        public string tiempo { get; set; }
        public int? velocidad_nominal { get; set; }
        public int? velocidad_efectiva { get; set; }
    }
}
