// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class indisponibilidadMaquinas
{
    [Key]
    public int id { get; set; }

    public int idMaquina { get; set; }

    public DateOnly fecha { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string motivo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdAt { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("indisponibilidadMaquinas")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}