// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class infoMaquinaTroqueladora
{
    [Key]
    public int idMaquina { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? fuerzaTroquelado_Ton { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? areaMaxTroquelado { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? areaMinTroquelado { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? velocidadMaxporCicloHora { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? sistemaStripping { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("infoMaquinaTroqueladora")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}