// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class infoMaquinaPegadora
{
    [Key]
    public int idMaquina { get; set; }

    [StringLength(100)]
    public string tipoCajaCompatible { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? numPuntosdePegado { get; set; }

    [StringLength(100)]
    public string tipoAdhesivo { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? velocidadMax { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("infoMaquinaPegadora")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}