// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class infoMaquinaDigital
{
    [Key]
    public int idMaquina { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? resolucionMaxima { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? velocidadBN { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? velocidadColor { get; set; }

    [StringLength(100)]
    public string tipoToner { get; set; }

    [StringLength(100)]
    public string tipoTinta { get; set; }

    [StringLength(100)]
    public string ripUtilizado { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("infoMaquinaDigital")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}