// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class infoConversionBobinaResult
    {
        [StringLength(50)]
        public string codigoBobina { get; set; }
        [StringLength(4000)]
        public string oF { get; set; }
        public int idProceso { get; set; }
        public int idSolicitud { get; set; }
        [Column("anchoPliego", TypeName = "decimal(20,2)")]
        public decimal? anchoPliego { get; set; }
        [Column("largoPliego", TypeName = "decimal(20,2)")]
        public decimal? largoPliego { get; set; }
        public int? cantidadProducida { get; set; }
        public int? cantidadNc { get; set; }
    }
}
