// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class infoMaquinaFlexografia
{
    [Key]
    public int idMaquina { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? anchoMaxImpresion { get; set; }

    public int? repeticionMaxima { get; set; }

    public int? repeticionMinima { get; set; }

    public int? numEstaciones { get; set; }

    [StringLength(100)]
    public string tipoAnilox { get; set; }

    [StringLength(100)]
    public string tipoSecado { get; set; }

    public bool? impresionFrenteyVuelta { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? temperaturaMax { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? temperaturaMin { get; set; }

    [Column(TypeName = "numeric(10, 2)")]
    public decimal? presionMax { get; set; }

    [StringLength(100)]
    public string tipoPelicula { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("infoMaquinaFlexografia")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}