// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class listaDeOperaciones
{
    [Key]
    public int idLista { get; set; }

    [StringLength(250)]
    public string nombreLista { get; set; }

    [StringLength(500)]
    public string descripcion { get; set; }

    [InverseProperty("idListaNavigation")]
    public virtual ICollection<listaItem> listaItem { get; set; } = new List<listaItem>();

    [InverseProperty("idListaNavigation")]
    public virtual ICollection<listaMaquina> listaMaquina { get; set; } = new List<listaMaquina>();

    [ForeignKey("idLista")]
    [InverseProperty("idLista")]
    public virtual ICollection<maquinas> idMaquina { get; set; } = new List<maquinas>();
}