// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class listasEmpaque
{
    [Key]
    [StringLength(10)]
    public string idEmpaque { get; set; }

    [StringLength(50)]
    public string codigoSAP { get; set; }

    [StringLength(150)]
    public string empaque { get; set; }

    [InverseProperty("tipoEmpaqueNavigation")]
    public virtual ICollection<detalleEntrega> detalleEntrega { get; set; } = new List<detalleEntrega>();
}