// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idLista", Name = "LISTA_ASIGNACION_FK")]
[Index("idListaMaquina", Name = "LISTA_MAQUINA_FK")]
public partial class listaMaquina
{
    [Key]
    public int idListaMaquina { get; set; }

    public int? idLista { get; set; }

    public int? idMaquina { get; set; }

    [ForeignKey("idLista")]
    [InverseProperty("listaMaquina")]
    public virtual listaDeOperaciones idListaNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("listaMaquina")]
    public virtual maquinas idMaquinaNavigation { get; set; }
}