// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idLista", Name = "LISTA_DETALLE_FK")]
[Index("idOperacion", Name = "LISTA_OPERACION_FK")]
public partial class listaItem
{
    [Key]
    public int idListaItem { get; set; }

    public int? idLista { get; set; }

    public int? idOperacion { get; set; }

    [ForeignKey("idLista")]
    [InverseProperty("listaItem")]
    public virtual listaDeOperaciones idListaNavigation { get; set; }

    [ForeignKey("idOperacion")]
    [InverseProperty("listaItem")]
    public virtual operaciones idOperacionNavigation { get; set; }
}