// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("oF", Name = "OF_FK")]
public partial class logCambiosOf
{
    [Key]
    public int log_id { get; set; }

    public int? oF { get; set; }

    [StringLength(50)]
    public string usuario_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_hora { get; set; }

    [StringLength(100)]
    public string estado_anterior { get; set; }

    [StringLength(100)]
    public string nuevo_estado { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("logCambiosOf")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [ForeignKey("usuario_id")]
    [InverseProperty("logCambiosOf")]
    public virtual usuario usuario { get; set; }
}