// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idLogProgramacion", Name = "IDX_DETALLE_LOG")]
[Index("idProceso", Name = "IDX_LOG_PROCESO_PROGRAMACION")]
public partial class logProgramacionDetalle
{
    [Key]
    public int idLogProgramacionDetalle { get; set; }

    public int idLogProgramacion { get; set; }

    public int idProceso { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string accion { get; set; }

    public int? estadoAnterior { get; set; }

    public int? estadoNuevo { get; set; }

    public int? posicionAnterior { get; set; }

    public int? posicionNueva { get; set; }

    [ForeignKey("estadoAnterior")]
    [InverseProperty("logProgramacionDetalleestadoAnteriorNavigation")]
    public virtual posturasOf estadoAnteriorNavigation { get; set; }

    [ForeignKey("estadoNuevo")]
    [InverseProperty("logProgramacionDetalleestadoNuevoNavigation")]
    public virtual posturasOf estadoNuevoNavigation { get; set; }

    [ForeignKey("idLogProgramacion")]
    [InverseProperty("logProgramacionDetalle")]
    public virtual logProgramacion idLogProgramacionNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("logProgramacionDetalle")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}