// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("fechaCreacion", Name = "IDX_LOG_PROGRAMACION_FECHA")]
[Index("programadoPor", Name = "IDX_LOG_PROGRAMACION_USUARIO")]
public partial class logProgramacion
{
    [Key]
    public int idLogProgramacion { get; set; }

    public int tablero { get; set; }

    [StringLength(50)]
    public string programadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public string comentario { get; set; }

    [InverseProperty("idLogProgramacionNavigation")]
    public virtual ICollection<logProgramacionDetalle> logProgramacionDetalle { get; set; } = new List<logProgramacionDetalle>();

    [ForeignKey("programadoPor")]
    [InverseProperty("logProgramacion")]
    public virtual usuario programadoPorNavigation { get; set; }

    [ForeignKey("tablero")]
    [InverseProperty("logProgramacion")]
    public virtual tablerosOf tableroNavigation { get; set; }
}