// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class logSincronizacionOf
{
    [Key]
    public int idLog { get; set; }

    public int oF { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaDeteccion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fechaUltimaRevision { get; set; }

    public string detalleDiferencia { get; set; }

    [StringLength(50)]
    public string estado { get; set; }
}