// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class logSoporteNexo
{
    [Key]
    public int idLogSoporte { get; set; }

    [StringLength(100)]
    public string moduloOriginador { get; set; }

    [StringLength(100)]
    public string idReferencia { get; set; }

    [StringLength(50)]
    public string severidad { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [StringLength(20)]
    public string user { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaRegistro { get; set; }

    [StringLength(100)]
    public string urlReferencia { get; set; }
}