// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("creadoPor", Name = "LOTE_CREADO_POR_FK")]
[Index("procesoOrigen", Name = "LOTE_PROCESO_ORIGEN_FK")]
[Index("idSolicitud", Name = "SOLICITUDMATERIALES_LOTEPLIEGOS_FK")]
public partial class lotePliego
{
    [Key]
    public int idLote { get; set; }

    public int? idSolicitud { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? largo { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? ancho { get; set; }

    public int? cantidadPliegos { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    [StringLength(50)]
    public string idMaterialSAP { get; set; }

    [StringLength(50)]
    public string codLote { get; set; }

    [StringLength(20)]
    public string estado { get; set; }

    public int? procesoOrigen { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? peso { get; set; }

    [StringLength(30)]
    public string codigoBobinaSAP { get; set; }

    public bool? tira { get; set; }

    public int? cantidadPendiente { get; set; }

    [ForeignKey("creadoPor")]
    [InverseProperty("lotePliego")]
    public virtual usuario creadoPorNavigation { get; set; }

    [ForeignKey("idSolicitud")]
    [InverseProperty("lotePliego")]
    public virtual solicitudMateriales idSolicitudNavigation { get; set; }

    [ForeignKey("procesoOrigen")]
    [InverseProperty("lotePliego")]
    public virtual procesoOf procesoOrigenNavigation { get; set; }

    [InverseProperty("idLoteNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProceso { get; set; } = new List<transferenciaProceso>();
}