// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFamilia", Name = "FAMILIA_MAQUINA_FK")]
public partial class maquinas
{
    [Key]
    public int idMaquina { get; set; }

    public int? idFamilia { get; set; }

    [StringLength(100)]
    public string nombreMaquina { get; set; }

    [StringLength(20)]
    public string nombreCorto { get; set; }

    public bool? necesitaAuxiliar { get; set; }

    [StringLength(100)]
    public string nombreAlterno { get; set; }

    public string descripcion { get; set; }

    public string textoAyuda { get; set; }

    public int? velocidadObjetivo { get; set; }

    public int? velocidadMaxima { get; set; }

    public int? velocidadTeorica { get; set; }

    public int? idUnidad { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? tamanoMaxLargoPulg { get; set; }

    [Column(TypeName = "numeric(18, 3)")]
    public decimal? tamanoMaxAnchoPulg { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? tamanoMinLargoPulg { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? tamanoMinAnchoPulg { get; set; }

    [StringLength(100)]
    public string metodoImpresion { get; set; }

    public int? cantidadColoresProcesar { get; set; }

    [StringLength(300)]
    public string automatizacionControl { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? anchoImpresion { get; set; }

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<auditoriaProceso> auditoriaProceso { get; set; } = new List<auditoriaProceso>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<fichaTecnicaProcesos> fichaTecnicaProcesos { get; set; } = new List<fichaTecnicaProcesos>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<horariosOperativos> horariosOperativos { get; set; } = new List<horariosOperativos>();

    [ForeignKey("idFamilia")]
    [InverseProperty("maquinas")]
    public virtual familliaDeMaquina idFamiliaNavigation { get; set; }

    [ForeignKey("idUnidad")]
    [InverseProperty("maquinas")]
    public virtual unidadesMedida idUnidadNavigation { get; set; }

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<indisponibilidadMaquinas> indisponibilidadMaquinas { get; set; } = new List<indisponibilidadMaquinas>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<listaMaquina> listaMaquina { get; set; } = new List<listaMaquina>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<pausasMaquina> pausasMaquina { get; set; } = new List<pausasMaquina>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<permisoMaquina> permisoMaquina { get; set; } = new List<permisoMaquina>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<sesionOperador> sesionOperador { get; set; } = new List<sesionOperador>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<solicitudMateriales> solicitudMateriales { get; set; } = new List<solicitudMateriales>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<tablerosOf> tablerosOf { get; set; } = new List<tablerosOf>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<validacionArranque> validacionArranque { get; set; } = new List<validacionArranque>();

    [ForeignKey("idMaquina")]
    [InverseProperty("idMaquina")]
    public virtual ICollection<catalogoTipoAcabado> idTipoAcabado { get; set; } = new List<catalogoTipoAcabado>();

    [ForeignKey("idMaquina")]
    [InverseProperty("idMaquina")]
    public virtual ICollection<catalogoTipoPapel> idTipoPapel { get; set; } = new List<catalogoTipoPapel>();

    [ForeignKey("idMaquina")]
    [InverseProperty("idMaquina")]
    public virtual ICollection<catalogoUsoTipico> idUsoTipico { get; set; } = new List<catalogoUsoTipico>();
}