// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idFamilia", Name = "FAMILIA_MAQUINA_FK")]
public partial class maquinas
{
    [Key]
    public int idMaquina { get; set; }

    public int? idFamilia { get; set; }

    [StringLength(100)]
    public string nombreMaquina { get; set; }

    [StringLength(20)]
    public string nombreCorto { get; set; }

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<contenidoEntrega> contenidoEntrega { get; set; } = new List<contenidoEntrega>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [ForeignKey("idFamilia")]
    [InverseProperty("maquinas")]
    public virtual familliaDeMaquina idFamiliaNavigation { get; set; }

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<operaciones> operaciones { get; set; } = new List<operaciones>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<permisoMaquina> permisoMaquina { get; set; } = new List<permisoMaquina>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();

    [InverseProperty("maquinaNavigation")]
    public virtual ICollection<sesionOperador> sesionOperador { get; set; } = new List<sesionOperador>();

    [InverseProperty("idMaquinaNavigation")]
    public virtual ICollection<tablerosOf> tablerosOf { get; set; } = new List<tablerosOf>();
}