// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class material
{
    [Key]
    [StringLength(25)]
    public string idMaterial { get; set; }

    [StringLength(200)]
    public string nombreMaterial { get; set; }

    [InverseProperty("idMaterialNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [InverseProperty("idMaterialNavigation")]
    public virtual ICollection<procesoOf> procesoOf { get; set; } = new List<procesoOf>();
}