// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class medicionAguas
{
    [Key]
    public int idMedicionAguas { get; set; }

    public int? idFichaProceso { get; set; }

    public int? tanqueAgua { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? pH { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? conductividad { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? alcohol { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? temperatura { get; set; }

    [ForeignKey("idFichaProceso")]
    [InverseProperty("medicionAguas")]
    public virtual fichaTecnicaProcesos idFichaProcesoNavigation { get; set; }
}