// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class menu
{
    [Key]
    public int idMenu { get; set; }

    [StringLength(200)]
    public string nombreMenu { get; set; }

    [StringLength(200)]
    public string icono { get; set; }

    [StringLength(200)]
    public string ruta { get; set; }

    [InverseProperty("idMenuNavigation")]
    public virtual ICollection<modulo> modulo { get; set; } = new List<modulo>();
}