// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idMenu", Name = "MENU_MODULO_FK")]
public partial class modulo
{
    [Key]
    public int idModulo { get; set; }

    public int? idMenu { get; set; }

    [StringLength(200)]
    public string nombreModulo { get; set; }

    [ForeignKey("idMenu")]
    [InverseProperty("modulo")]
    public virtual menu idMenuNavigation { get; set; }

    [InverseProperty("idModuloNavigation")]
    public virtual ICollection<subModulo> subModulo { get; set; } = new List<subModulo>();
}