// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class motivoConciliacion
{
    [Key]
    public int idMotivo { get; set; }

    [Required]
    [StringLength(100)]
    public string nombre { get; set; }

    [StringLength(250)]
    public string descripcion { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idMotivoNavigation")]
    public virtual ICollection<conciliacion> conciliacion { get; set; } = new List<conciliacion>();
}