// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class motorista
{
    [Key]
    public int idMotorista { get; set; }

    [StringLength(200)]
    public string nombres { get; set; }

    [StringLength(200)]
    public string apellidos { get; set; }

    [StringLength(4)]
    public string codigo { get; set; }

    [InverseProperty("idMotoristaNavigation")]
    public virtual ICollection<gira> gira { get; set; } = new List<gira>();
}