// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTarjetaOf", Name = "TARJETA_MOVIMIENTO_FK")]
[Index("user", Name = "USUARIO_MOVIMIENTO_FK")]
public partial class movimientoOf
{
    [Key]
    public int idMovimiento { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string user { get; set; }

    public int? idTarjetaOf { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaMovimiento { get; set; }

    public int? tableroAnterior { get; set; }

    public int? posturaAnterior { get; set; }

    public int? posicionAnterior { get; set; }

    public int? tableroNuevo { get; set; }

    public int? posturaNueva { get; set; }

    public int? posicionNueva { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("movimientoOf")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }

    [ForeignKey("user")]
    [InverseProperty("movimientoOf")]
    public virtual usuario userNavigation { get; set; }
}