// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class movimientoOf
{
    [Key]
    public int idMovimiento { get; set; }

    public int? tipoObjeto { get; set; }

    public int? idObjeto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaMovimiento { get; set; }

    public int? tableroAnterior { get; set; }

    public int? posturaAnterior { get; set; }

    public int? posicionAnterior { get; set; }

    public int? tableroNuevo { get; set; }

    public int? posturaNueva { get; set; }

    public int? posicionNueva { get; set; }

    [StringLength(50)]
    public string usuario { get; set; }
}