// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("oF", Name = "FK_OF")]
public partial class notasOf
{
    [Key]
    public int idComentario { get; set; }

    public int? oF { get; set; }

    [StringLength(50)]
    public string creadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreación { get; set; }

    public string texto { get; set; }

    [StringLength(50)]
    public string tipoNota { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("notasOf")]
    public virtual tarjetaOf oFNavigation { get; set; }
}