// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("familiaMaquina", Name = "FAMILIA_MAQUINA_FK")]
public partial class operaciones
{
    [Key]
    public int idOperacion { get; set; }

    public int? familiaMaquina { get; set; }

    [StringLength(200)]
    public string nombreOperacion { get; set; }

    [StringLength(50)]
    public string tipoOperacion { get; set; }

    [StringLength(3)]
    public string prefijo { get; set; }

    [InverseProperty("idOperacionNavigation")]
    public virtual ICollection<detalleOperacionProceso> detalleOperacionProceso { get; set; } = new List<detalleOperacionProceso>();

    [InverseProperty("idOperacionNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [ForeignKey("familiaMaquina")]
    [InverseProperty("operaciones")]
    public virtual familliaDeMaquina familiaMaquinaNavigation { get; set; }
}