// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class oV
{
    [Key]
    public int idOv { get; set; }

    [Column("oV")]
    [StringLength(200)]
    [Unicode(false)]
    public string oV1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string codCliente { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string cliente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaOv { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaEntrega { get; set; }

    public string comentario { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string vendedor { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string tipoOrden { get; set; }

    [InverseProperty("idOvNavigation")]
    public virtual ICollection<articuloOv> articuloOv { get; set; } = new List<articuloOv>();

    [InverseProperty("idOvNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [InverseProperty("idOvNavigation")]
    public virtual ICollection<tarjetaOf> tarjetaOf { get; set; } = new List<tarjetaOf>();
}