// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class oV
{
    [Key]
    [Column("oV")]
    public int oV1 { get; set; }

    [StringLength(100)]
    public string codigoCliente { get; set; }

    [StringLength(200)]
    public string cliente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaOv { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaEntrega { get; set; }

    public string comentario { get; set; }

    [StringLength(50)]
    public string vendedor { get; set; }

    [StringLength(50)]
    public string tipoOrden { get; set; }

    [InverseProperty("oVNavigation")]
    public virtual ICollection<articuloOv> articuloOv { get; set; } = new List<articuloOv>();
}