// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("bitacoraId", Name = "FK_BITACORA")]
[Index("maquina", Name = "FK_MAQUINA")]
[Index("usuario", Name = "FK_USUARIO")]
public partial class pausasMaquina
{
    [Key]
    public int id { get; set; }

    public int? maquina { get; set; }

    [StringLength(50)]
    public string usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? inicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fin { get; set; }

    [StringLength(50)]
    public string bitacoraId { get; set; }

    [StringLength(100)]
    public string tipoPausa { get; set; }

    [ForeignKey("bitacoraId")]
    [InverseProperty("pausasMaquina")]
    public virtual reportesDeOperadores bitacora { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("pausasMaquina")]
    public virtual maquinas maquinaNavigation { get; set; }

    [ForeignKey("usuario")]
    [InverseProperty("pausasMaquina")]
    public virtual usuario usuarioNavigation { get; set; }
}