// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("maquina", Name = "MAQUINA_PERMISO_USER_FK")]
[Index("user", Name = "USER_MAQUINA_FK")]
public partial class permisoMaquina
{
    [Key]
    public int idPermisoMaquina { get; set; }

    [StringLength(50)]
    public string user { get; set; }

    public int? maquina { get; set; }

    public bool? asignada { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("permisoMaquina")]
    public virtual maquinas maquinaNavigation { get; set; }

    [ForeignKey("user")]
    [InverseProperty("permisoMaquina")]
    public virtual usuario userNavigation { get; set; }
}