// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idPermisoTipo", Name = "PERMISO_TIPO_FK")]
[Index("idRol", Name = "ROL_FK")]
public partial class permisoEspecifico
{
    [Key]
    public int idPermisoEspecifico { get; set; }

    public int? idRol { get; set; }

    public int? idPermisoTipo { get; set; }

    public bool? habilitado { get; set; }

    [ForeignKey("idPermisoTipo")]
    [InverseProperty("permisoEspecifico")]
    public virtual permisoTipo idPermisoTipoNavigation { get; set; }

    [ForeignKey("idRol")]
    [InverseProperty("permisoEspecifico")]
    public virtual rol idRolNavigation { get; set; }
}