// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idSubModulo", Name = "SUBMODULO_FK")]
public partial class permisoTipo
{
    [Key]
    public int idPermisoTipo { get; set; }

    public int? idSubModulo { get; set; }

    [StringLength(100)]
    public string clave { get; set; }

    public string descripcion { get; set; }

    [ForeignKey("idSubModulo")]
    [InverseProperty("permisoTipo")]
    public virtual subModulo idSubModuloNavigation { get; set; }

    [InverseProperty("idPermisoTipoNavigation")]
    public virtual ICollection<permisoEspecifico> permisoEspecifico { get; set; } = new List<permisoEspecifico>();
}