// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idReporteAuditoria", Name = "PORCENTAJES_DE_AGUA_FK")]
public partial class porcentajeDeAgua
{
    [Key]
    public int idPorcentaje { get; set; }

    public int? idReporteAuditoria { get; set; }

    public int? secuencia { get; set; }

    [StringLength(50)]
    public string valor { get; set; }

    [ForeignKey("idReporteAuditoria")]
    [InverseProperty("porcentajeDeAgua")]
    public virtual reporteDeAuditoria idReporteAuditoriaNavigation { get; set; }
}