// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idTablero", Name = "TABLEROS_POSTURAS_FK")]
public partial class posturasOf
{
    [Key]
    public int idPostura { get; set; }

    public int? idTablero { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string nombrePostura { get; set; }

    public int? secuencia { get; set; }

    [ForeignKey("idTablero")]
    [InverseProperty("posturasOf")]
    public virtual tablerosOf idTableroNavigation { get; set; }

    [InverseProperty("idPosturaNavigation")]
    public virtual ICollection<procesoOf> procesoOf { get; set; } = new List<procesoOf>();

    [InverseProperty("idPosturaNavigation")]
    public virtual ICollection<tarjetaOf> tarjetaOf { get; set; } = new List<tarjetaOf>();
}