// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idBarniz", Name = "BARNIZ_LAMPARA_UV_FK")]
public partial class potenciaLamparaUv
{
    [Key]
    public int idPotencia { get; set; }

    public int? idBarniz { get; set; }

    public int? numeroFila { get; set; }

    public int? secuencia { get; set; }

    [StringLength(50)]
    public string potencia { get; set; }

    [ForeignKey("idBarniz")]
    [InverseProperty("potenciaLamparaUv")]
    public virtual detalleBarniz idBarnizNavigation { get; set; }
}