// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoBarniz
{
    [Key]
    public int idProcesoBarniz { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadPliegosImprimir { get; set; }

    [StringLength(500)]
    public string cantidadPliegosDemasia { get; set; }

    [StringLength(500)]
    public string repeticionPliegos { get; set; }

    [StringLength(500)]
    public string tiempoArreglo { get; set; }

    [StringLength(500)]
    public string tiempoCorrida { get; set; }

    [StringLength(200)]
    public string anchoPliego { get; set; }

    [StringLength(200)]
    public string largoPliego { get; set; }

    [StringLength(200)]
    public string detalleBarniz { get; set; }

    [StringLength(500)]
    public string indicacionImpresion { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoBarniz")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}