// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesosFlexo
{
    [Key]
    public int idProcesosFlexo { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadMaterialSoli { get; set; }

    [StringLength(200)]
    public string tiempoArreglo { get; set; }

    [StringLength(200)]
    public string tiempoCorrida { get; set; }

    [StringLength(500)]
    public string z { get; set; }

    [StringLength(500)]
    public string etiquetaRollo { get; set; }

    [StringLength(500)]
    public string rollosTotales { get; set; }

    [StringLength(500)]
    public string rollosCorrugado { get; set; }

    [StringLength(500)]
    public string cantCorrugado { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesosFlexo")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}