// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idProcesoPreprensa", Name = "idProcesoPreprensa", IsUnique = true)]
public partial class procesoPreprensa
{
    [Key]
    public int idProcesoPreprensa { get; set; }

    public int? idProcesoOf { get; set; }

    [StringLength(500)]
    public string cantidadPlanchas { get; set; }

    [ForeignKey("idProcesoOf")]
    [InverseProperty("procesoPreprensa")]
    public virtual procesoOf idProcesoOfNavigation { get; set; }
}