// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idPostura", Name = "POSTURA_PROCESO_FK")]
[Index("idTablero", Name = "TABLERO_PROCESO_FK")]
[Index("idTarjetaOf", Name = "TARJETA_PROCESO_FK")]
public partial class procesoOf
{
    [Key]
    public int idProceso { get; set; }

    public int? idTarjetaOf { get; set; }

    public int? idTablero { get; set; }

    public int? idPostura { get; set; }

    public int? secuencia { get; set; }

    public bool? completada { get; set; }

    public bool? bloqueada { get; set; }

    public int? pliegosRecibidos { get; set; }

    public int? pliegosEntregados { get; set; }

    public int? pliegosDanados { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFinalizacion { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? horasTotales { get; set; }

    public int? posicion { get; set; }

    [StringLength(100)]
    public string programadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [ForeignKey("idPostura")]
    [InverseProperty("procesoOf")]
    public virtual posturasOf idPosturaNavigation { get; set; }

    [ForeignKey("idTablero")]
    [InverseProperty("procesoOf")]
    public virtual tablerosOf idTableroNavigation { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("procesoOf")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}