// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoPreprensa
{
    [Key]
    public int idProcesoPreprensa { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadPlanchas { get; set; }

    [StringLength(500)]
    public string tiempoArreglo { get; set; }

    [StringLength(500)]
    public string tiempoCorrida { get; set; }

    [StringLength(100)]
    public string ordenAnterior { get; set; }

    [StringLength(500)]
    public string repeticionPliegos { get; set; }

    [StringLength(500)]
    public string medidaProd { get; set; }

    [StringLength(500)]
    public string indicacion { get; set; }

    [StringLength(200)]
    public string tamanoAbierto { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoPreprensa")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}