// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("areaAnterior", Name = "AREA_ANTERIOR_FK")]
[Index("areaSiguiente", Name = "AREA_SIGUIENTE_FK")]
[Index("idMaterial", Name = "MATERIAL_PROCESO_FK")]
[Index("oF", Name = "OF_PROCESO_FK")]
[Index("idPostura", Name = "POSTURA_PROCESO_FK")]
[Index("procesoAnterior", Name = "PROCESO_ANTERIOR_FK")]
[Index("procesoSiguiente", Name = "PROCESO_SIGUIENTE_FK")]
[Index("idTablero", Name = "TABLERO_PROCESO_FK")]
public partial class procesoOf
{
    [Key]
    public int idProceso { get; set; }

    public int? oF { get; set; }

    public int? idTablero { get; set; }

    public int? idPostura { get; set; }

    [StringLength(25)]
    public string idMaterial { get; set; }

    [StringLength(500)]
    public string nombreTarjeta { get; set; }

    public string productoOf { get; set; }

    public string descripcionOf { get; set; }

    public int? secuencia { get; set; }

    public bool? completada { get; set; }

    public bool? bloqueada { get; set; }

    public int? pliegosRecibidos { get; set; }

    public int? pliegosEntregados { get; set; }

    public int? pliegosDanados { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFinalizacion { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? tiempoEstimado { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? horasTotales { get; set; }

    public int? posicion { get; set; }

    [StringLength(100)]
    public string programadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public int? tipoObjeto { get; set; }

    public bool? archivada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaVencimiento { get; set; }

    [StringLength(200)]
    public string tipoMaquinaSAP { get; set; }

    [StringLength(200)]
    public string idMaquinaSAP { get; set; }

    public int? oV { get; set; }

    [StringLength(50)]
    public string serieNumeracion { get; set; }

    [StringLength(10)]
    public string tiroRetiro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualización { get; set; }

    public string comentario { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    public bool? muestra { get; set; }

    public bool? cancelada { get; set; }

    [StringLength(22)]
    public string indicador { get; set; }

    public bool? corridaCombinada { get; set; }

    public int? lineNumSAP { get; set; }

    [StringLength(25)]
    public string indicadorProceso { get; set; }

    public bool? reproceso { get; set; }

    [StringLength(50)]
    public string correlativoCC { get; set; }

    public int? orden { get; set; }

    public int? subOrden { get; set; }

    public int? procesoAnterior { get; set; }

    public int? procesoSiguiente { get; set; }

    [StringLength(250)]
    public string dependenciasAnteriores { get; set; }

    [StringLength(250)]
    public string dependenciasSiguientes { get; set; }

    [StringLength(25)]
    public string modoSecuenciacion { get; set; }

    public int? areaAnterior { get; set; }

    public int? areaSiguiente { get; set; }

    public int? idSolicitudMateriales { get; set; }

    public int? tipoEntrada { get; set; }

    public int? tipoSalida { get; set; }

    public bool? esEnsamblaje { get; set; }

    [InverseProperty("procesoAnteriorNavigation")]
    public virtual ICollection<procesoOf> InverseprocesoAnteriorNavigation { get; set; } = new List<procesoOf>();

    [InverseProperty("procesoSiguienteNavigation")]
    public virtual ICollection<procesoOf> InverseprocesoSiguienteNavigation { get; set; } = new List<procesoOf>();

    [ForeignKey("areaAnterior")]
    [InverseProperty("procesoOfareaAnteriorNavigation")]
    public virtual areas areaAnteriorNavigation { get; set; }

    [ForeignKey("areaSiguiente")]
    [InverseProperty("procesoOfareaSiguienteNavigation")]
    public virtual areas areaSiguienteNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<asignacion> asignacion { get; set; } = new List<asignacion>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<auditoriaProceso> auditoriaProceso { get; set; } = new List<auditoriaProceso>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<componenteProduccion> componenteProduccion { get; set; } = new List<componenteProduccion>();

    [InverseProperty("maestroNavigation")]
    public virtual ICollection<corridaCombinada> corridaCombinadamaestroNavigation { get; set; } = new List<corridaCombinada>();

    [InverseProperty("subordinadoNavigation")]
    public virtual corridaCombinada corridaCombinadasubordinadoNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ffeTiemposProcesosGlobal ffeTiemposProcesosGlobal { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<fichaTecnicaProcesos> fichaTecnicaProcesos { get; set; } = new List<fichaTecnicaProcesos>();

    [ForeignKey("idMaterial")]
    [InverseProperty("procesoOf")]
    public virtual material idMaterialNavigation { get; set; }

    [ForeignKey("idPostura")]
    [InverseProperty("procesoOf")]
    public virtual posturasOf idPosturaNavigation { get; set; }

    [ForeignKey("idSolicitudMateriales")]
    [InverseProperty("procesoOf")]
    public virtual solicitudMateriales idSolicitudMaterialesNavigation { get; set; }

    [ForeignKey("idTablero")]
    [InverseProperty("procesoOf")]
    public virtual tablerosOf idTableroNavigation { get; set; }

    [InverseProperty("proceso")]
    public virtual ICollection<logCambiosProceso> logCambiosProceso { get; set; } = new List<logCambiosProceso>();

    [InverseProperty("procesoOrigenNavigation")]
    public virtual ICollection<lotePliego> lotePliego { get; set; } = new List<lotePliego>();

    [ForeignKey("oF")]
    [InverseProperty("procesoOf")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoAcabado> procesoAcabado { get; set; } = new List<procesoAcabado>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoAcabadoFlexo> procesoAcabadoFlexo { get; set; } = new List<procesoAcabadoFlexo>();

    [ForeignKey("procesoAnterior")]
    [InverseProperty("InverseprocesoAnteriorNavigation")]
    public virtual procesoOf procesoAnteriorNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoBarniz> procesoBarniz { get; set; } = new List<procesoBarniz>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoImpresora> procesoImpresora { get; set; } = new List<procesoImpresora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoImpresoraFlexo> procesoImpresoraFlexo { get; set; } = new List<procesoImpresoraFlexo>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoMangaFlexo> procesoMangaFlexo { get; set; } = new List<procesoMangaFlexo>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoPegadora> procesoPegadora { get; set; } = new List<procesoPegadora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoPreprensa> procesoPreprensa { get; set; } = new List<procesoPreprensa>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoSerigrafia> procesoSerigrafia { get; set; } = new List<procesoSerigrafia>();

    [ForeignKey("procesoSiguiente")]
    [InverseProperty("InverseprocesoSiguienteNavigation")]
    public virtual procesoOf procesoSiguienteNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoTroqueladora> procesoTroqueladora { get; set; } = new List<procesoTroqueladora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesosFlexo> procesosFlexo { get; set; } = new List<procesosFlexo>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<tarjetaEtiqueta> tarjetaEtiqueta { get; set; } = new List<tarjetaEtiqueta>();

    [ForeignKey("tipoEntrada")]
    [InverseProperty("procesoOftipoEntradaNavigation")]
    public virtual tipoComponente tipoEntradaNavigation { get; set; }

    [ForeignKey("tipoSalida")]
    [InverseProperty("procesoOftipoSalidaNavigation")]
    public virtual tipoComponente tipoSalidaNavigation { get; set; }

    [InverseProperty("idDestinoNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProcesoidDestinoNavigation { get; set; } = new List<transferenciaProceso>();

    [InverseProperty("idOrigenNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProcesoidOrigenNavigation { get; set; } = new List<transferenciaProceso>();
}