// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idMaterial", Name = "MATERIAL_PROCESO_FK")]
[Index("oF", Name = "OF_PROCESO_FK")]
[Index("idPostura", Name = "POSTURA_PROCESO_FK")]
[Index("idTablero", Name = "TABLERO_PROCESO_FK")]
public partial class procesoOf
{
    [Key]
    public int idProceso { get; set; }

    public int? oF { get; set; }

    public int? idTablero { get; set; }

    public int? idPostura { get; set; }

    [StringLength(25)]
    public string idMaterial { get; set; }

    [StringLength(254)]
    public string nombreTarjeta { get; set; }

    [StringLength(200)]
    public string productoOf { get; set; }

    public string descripcionOf { get; set; }

    public int? secuencia { get; set; }

    public bool? completada { get; set; }

    public bool? bloqueada { get; set; }

    public int? pliegosRecibidos { get; set; }

    public int? pliegosEntregados { get; set; }

    public int? pliegosDanados { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaFinalizacion { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? tiempoEstimado { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? horasTotales { get; set; }

    public int? posicion { get; set; }

    [StringLength(100)]
    public string programadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    public int? tipoObjeto { get; set; }

    public bool? archivada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaVencimiento { get; set; }

    [StringLength(200)]
    public string tipoMaquinaSAP { get; set; }

    [StringLength(200)]
    public string idMaquinaSAP { get; set; }

    public int? oV { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<asignacion> asignacion { get; set; } = new List<asignacion>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<detalleOperacionProceso> detalleOperacionProceso { get; set; } = new List<detalleOperacionProceso>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [ForeignKey("idMaterial")]
    [InverseProperty("procesoOf")]
    public virtual material idMaterialNavigation { get; set; }

    [ForeignKey("idPostura")]
    [InverseProperty("procesoOf")]
    public virtual posturasOf idPosturaNavigation { get; set; }

    [ForeignKey("idTablero")]
    [InverseProperty("procesoOf")]
    public virtual tablerosOf idTableroNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("procesoOf")]
    public virtual tarjetaOf oFNavigation { get; set; }

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoAcabado> procesoAcabado { get; set; } = new List<procesoAcabado>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoBarniz> procesoBarniz { get; set; } = new List<procesoBarniz>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoImpresora> procesoImpresora { get; set; } = new List<procesoImpresora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoPegadora> procesoPegadora { get; set; } = new List<procesoPegadora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoPreprensa> procesoPreprensa { get; set; } = new List<procesoPreprensa>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoSerigrafia> procesoSerigrafia { get; set; } = new List<procesoSerigrafia>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<procesoTroqueladora> procesoTroqueladora { get; set; } = new List<procesoTroqueladora>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<tarjetaCampo> tarjetaCampo { get; set; } = new List<tarjetaCampo>();

    [InverseProperty("idProcesoNavigation")]
    public virtual ICollection<tarjetaEtiqueta> tarjetaEtiqueta { get; set; } = new List<tarjetaEtiqueta>();
}