// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoAcabado
{
    [Key]
    public int idProcesoAcabado { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadMrequerido { get; set; }

    [StringLength(500)]
    public string cantidadDemasia { get; set; }

    [StringLength(500)]
    public string tiempoArreglo { get; set; }

    [StringLength(500)]
    public string tiempoCorrida { get; set; }

    [StringLength(100)]
    public string barniz { get; set; }

    [StringLength(100)]
    public string tiro { get; set; }

    [StringLength(100)]
    public string retiro { get; set; }

    [StringLength(100)]
    public string foil { get; set; }

    [StringLength(100)]
    public string numerado { get; set; }

    [StringLength(100)]
    public string laminado { get; set; }

    [StringLength(500)]
    public string foilDetalle { get; set; }

    [StringLength(500)]
    public string detalleBarniz { get; set; }

    [StringLength(500)]
    public string laminadoDetalle { get; set; }

    [StringLength(500)]
    public string indicacion { get; set; }

    [StringLength(100)]
    public string medidaProd { get; set; }

    [StringLength(500)]
    public string detalleNum { get; set; }

    [StringLength(500)]
    public string tipoCierre { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoAcabado")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}