// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoAcabado
{
    [Key]
    public int idProcesoAcabado { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadMrequerido { get; set; }

    [StringLength(500)]
    public string cantidadDemasia { get; set; }

    public TimeOnly? tiempoArreglo { get; set; }

    public TimeOnly? tiempoCorrida { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoAcabado")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}