// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoImpresora
{
    [Key]
    public int idProcesoImpresora { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantidadPliegosImprimir { get; set; }

    [StringLength(500)]
    public string cantidadPliegosDemasia { get; set; }

    [StringLength(500)]
    public string repeticionPliegos { get; set; }

    [StringLength(500)]
    public string tiempoArreglo { get; set; }

    [StringLength(500)]
    public string tiempoCorrida { get; set; }

    [StringLength(200)]
    public string tipoMaterial { get; set; }

    [StringLength(200)]
    public string calibreBase { get; set; }

    [StringLength(200)]
    public string anchoPliego { get; set; }

    [StringLength(200)]
    public string largoPliego { get; set; }

    [StringLength(200)]
    public string tintas { get; set; }

    [StringLength(100)]
    public string tiro { get; set; }

    [StringLength(100)]
    public string retiro { get; set; }

    [StringLength(100)]
    public string foil { get; set; }

    [StringLength(100)]
    public string numerado { get; set; }

    [StringLength(100)]
    public string laminado { get; set; }

    [StringLength(500)]
    public string foilDetalle { get; set; }

    [StringLength(500)]
    public string barnizDetalle { get; set; }

    [StringLength(500)]
    public string laminadoDetalle { get; set; }

    [StringLength(500)]
    public string indicacionImpresion { get; set; }

    [StringLength(500)]
    public string medidaProd { get; set; }

    [StringLength(200)]
    public string idTroquel { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoImpresora")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}