// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoTroqueladora
{
    [Key]
    public int idProcesoTroqueladora { get; set; }

    public int idProceso { get; set; }

    [StringLength(200)]
    public string idTroquel { get; set; }

    [StringLength(500)]
    public string cantPliegosTroquelar { get; set; }

    [StringLength(500)]
    public string repeticionPliegos { get; set; }

    [StringLength(500)]
    public string tiempoArreglo { get; set; }

    [StringLength(500)]
    public string tiempoCorrida { get; set; }

    [StringLength(200)]
    public string tipoMaterial { get; set; }

    [StringLength(200)]
    public string calibreBase { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoTroqueladora")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}