// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoSerigrafia
{
    [Key]
    public int idProcesoSerigrafia { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string cantProducir { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoSerigrafia")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}