// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class procesoImpresoraFlexo
{
    [Key]
    public int idProcesoImpresoraFlexo { get; set; }

    public int idProceso { get; set; }

    [StringLength(500)]
    public string forma { get; set; }

    [StringLength(500)]
    public string radesq { get; set; }

    [StringLength(500)]
    public string semicorte { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("procesoImpresoraFlexo")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}