// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class registroLamparas
{
    [Key]
    public int idRegistroLampara { get; set; }

    public int? idFichaProceso { get; set; }

    public int? idVariable { get; set; }

    [StringLength(50)]
    public string seccionMaquina { get; set; }

    public int? numeroLampara { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal? potencia { get; set; }

    [ForeignKey("idFichaProceso")]
    [InverseProperty("registroLamparas")]
    public virtual fichaTecnicaProcesos idFichaProcesoNavigation { get; set; }

    [ForeignKey("idVariable")]
    [InverseProperty("registroLamparas")]
    public virtual variablesTecnicas idVariableNavigation { get; set; }
}