// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEstadoReporte", Name = "ESTADO_REPORTE_FK")]
[Index("idMaquina", Name = "MAQUINA_REPORTE_FK")]
[Index("operador", Name = "OPERADOR_REPORTE_FK")]
[Index("idTipoReporte", Name = "TIPO_REPORTE_FK")]
public partial class reportesDeOperadores
{
    [Key]
    [StringLength(50)]
    public string idReporte { get; set; }

    public int? idEstadoReporte { get; set; }

    public int? idTipoReporte { get; set; }

    public int? idMaquina { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaDeCreacion { get; set; }

    [StringLength(100)]
    public string turno { get; set; }

    public int? auxiliar { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadEfectiva { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadNominal { get; set; }

    public TimeOnly? tiempoTotal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ultimaActualizacion { get; set; }

    [StringLength(100)]
    public string creadoPor { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    public int? tipoObjeto { get; set; }

    [InverseProperty("idReporteNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [ForeignKey("idEstadoReporte")]
    [InverseProperty("reportesDeOperadores")]
    public virtual estadosReporte idEstadoReporteNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("reportesDeOperadores")]
    public virtual maquinas idMaquinaNavigation { get; set; }

    [ForeignKey("idTipoReporte")]
    [InverseProperty("reportesDeOperadores")]
    public virtual tipoReporte idTipoReporteNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("reportesDeOperadores")]
    public virtual usuario operadorNavigation { get; set; }
}