// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idAuditoria", Name = "REPORTES_DE_AUDITORIAS_FK")]
public partial class reporteDeAuditoria
{
    [Key]
    public int idReporteAuditoria { get; set; }

    public int? idAuditoria { get; set; }

    [StringLength(254)]
    public string producto { get; set; }

    [StringLength(100)]
    public string codigoProducto { get; set; }

    public int? numeroOf { get; set; }

    [StringLength(50)]
    public string maquina { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public string observaciones { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaActualizacion { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string procesosArrelgo { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string tiroRetiro { get; set; }

    [InverseProperty("idReporteAuditoriaNavigation")]
    public virtual ICollection<auditoriaDeProcesos> auditoriaDeProcesos { get; set; } = new List<auditoriaDeProcesos>();

    [InverseProperty("idReporteAuditoriaNavigation")]
    public virtual ICollection<auditoriaDeProductos> auditoriaDeProductos { get; set; } = new List<auditoriaDeProductos>();

    [ForeignKey("idAuditoria")]
    [InverseProperty("reporteDeAuditoria")]
    public virtual auditoriaDeCalidad idAuditoriaNavigation { get; set; }

    [InverseProperty("idReporteAuditoriaNavigation")]
    public virtual ICollection<porcentajeDeAgua> porcentajeDeAgua { get; set; } = new List<porcentajeDeAgua>();

    [InverseProperty("idReporteAuditoriaNavigation")]
    public virtual ICollection<variablesDeAgua> variablesDeAgua { get; set; } = new List<variablesDeAgua>();
}