// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("codigo", Name = "UQ__resoluci__40F9A20692DB4E90", IsUnique = true)]
public partial class resolucionCalidad
{
    [Key]
    public int idResolucion { get; set; }

    [Required]
    [StringLength(30)]
    public string codigo { get; set; }

    [Required]
    [StringLength(60)]
    public string nombre { get; set; }

    public bool implicaCosto { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idResolucionNavigation")]
    public virtual ICollection<casoCalidad> casoCalidad { get; set; } = new List<casoCalidad>();
}