// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class ResumenOfResult
    {
        public int? oF { get; set; }
        public int combinada { get; set; }
        [StringLength(500)]
        public string maquina { get; set; }
        [StringLength(22)]
        public string indicador { get; set; }
        [Column("horas_mq_planificadas", TypeName = "decimal(38,2)")]
        public decimal? horas_mq_planificadas { get; set; }
        [Column("horas_mq_arreglo_planificadas", TypeName = "decimal(38,2)")]
        public decimal? horas_mq_arreglo_planificadas { get; set; }
        [Column("horas_mq_corrida_planificadas", TypeName = "decimal(38,2)")]
        public decimal? horas_mq_corrida_planificadas { get; set; }
        [StringLength(36)]
        public string horas_mq_ejecutadas_HHMMSS { get; set; }
        public double? horas_mq_ejecutadas_decimal { get; set; }
        public int? cantidad_producida_tiro { get; set; }
        public int? cantidad_producida_retiro { get; set; }
        public int? cantidad_producida_total { get; set; }
        [Column("cantidad_planificada", TypeName = "decimal(38,2)")]
        public decimal? cantidad_planificada { get; set; }
    }
}
