// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class rol
{
    [Key]
    public int idRol { get; set; }

    [StringLength(200)]
    public string nombreRol { get; set; }

    public string descripcion { get; set; }

    public bool? status { get; set; }

    [InverseProperty("idRolNavigation")]
    public virtual ICollection<permiso> permiso { get; set; } = new List<permiso>();

    [InverseProperty("idRolNavigation")]
    public virtual ICollection<usuario> usuario { get; set; } = new List<usuario>();
}