// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetalleImpresion", Name = "FICHA_SECUENCIA_COLOR_FK")]
public partial class secuenciaDeColor
{
    [Key]
    public int idSecuencia { get; set; }

    public int? idDetalleImpresion { get; set; }

    public int? numeroFila { get; set; }

    public int? secuencia { get; set; }

    [StringLength(50)]
    public string tiro { get; set; }

    [StringLength(50)]
    public string presionTiro { get; set; }

    [StringLength(50)]
    public string densidadTiro { get; set; }

    [StringLength(50)]
    public string porcentajeAguaTiro { get; set; }

    [StringLength(50)]
    public string retiro { get; set; }

    [StringLength(50)]
    public string presionRetiro { get; set; }

    [StringLength(50)]
    public string densidadRetiro { get; set; }

    [StringLength(50)]
    public string porcentajeAguaRetiro { get; set; }

    [StringLength(50)]
    public string anguloColorTiro { get; set; }

    [StringLength(50)]
    public string varianteFlujoTiro { get; set; }

    [StringLength(50)]
    public string rodilloEntintadorTiro { get; set; }

    [StringLength(50)]
    public string distribuciónLateralTiro { get; set; }

    [StringLength(50)]
    public string tomadorTintaTiro { get; set; }

    [StringLength(50)]
    public string vueltasTiro { get; set; }

    [StringLength(50)]
    public string anguloColorRetiro { get; set; }

    [StringLength(50)]
    public string varianteFlujoRetiro { get; set; }

    [StringLength(50)]
    public string rodilloEntintadorRetiro { get; set; }

    [StringLength(50)]
    public string distribuciónLateralRetiro { get; set; }

    [StringLength(50)]
    public string tomadorTintaRetiro { get; set; }

    [StringLength(50)]
    public string vueltasRetiro { get; set; }

    [ForeignKey("idDetalleImpresion")]
    [InverseProperty("secuenciaDeColor")]
    public virtual detalleImpresion idDetalleImpresionNavigation { get; set; }
}