// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("bitacora", Name = "BITACORA_FK")]
[Index("maquina", Name = "MAQUINA_FK")]
[Index("operador", Name = "OPERADOR_FK")]
public partial class sesionOperador
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    public string operador { get; set; }

    public int? maquina { get; set; }

    [StringLength(50)]
    public string bitacora { get; set; }

    [StringLength(25)]
    public string turno { get; set; }

    public bool? activa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [ForeignKey("bitacora")]
    [InverseProperty("sesionOperador")]
    public virtual reportesDeOperadores bitacoraNavigation { get; set; }

    [ForeignKey("maquina")]
    [InverseProperty("sesionOperador")]
    public virtual maquinas maquinaNavigation { get; set; }

    [ForeignKey("operador")]
    [InverseProperty("sesionOperador")]
    public virtual usuario operadorNavigation { get; set; }
}