// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[PrimaryKey("oF", "idSolicitud")]
[Index("oF", Name = "SOLICITUDMATERIALESOF_FK")]
[Index("idSolicitud", Name = "SOLICITUDMATERIALES_FK")]
public partial class solicitudMaterialesOf
{
    [Key]
    public int oF { get; set; }

    [Key]
    public int idSolicitud { get; set; }

    public int? cantidadAsignada { get; set; }

    [ForeignKey("idSolicitud")]
    [InverseProperty("solicitudMaterialesOf")]
    public virtual solicitudMateriales idSolicitudNavigation { get; set; }

    [ForeignKey("oF")]
    [InverseProperty("solicitudMaterialesOf")]
    public virtual tarjetaOf oFNavigation { get; set; }
}