// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class solicitudMateriales
{
    [Key]
    public int idSolicitud { get; set; }

    [StringLength(50)]
    public string trabajo { get; set; }

    public int? tipoPreparacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaSolicitud { get; set; }

    [StringLength(50)]
    public string idMaterialSAP { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? anchoHoja { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? largoHoja { get; set; }

    public int? cantidadPorCortar { get; set; }

    public int? estado { get; set; }

    public int? tiraje { get; set; }

    public int? idMaquina { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? anchoPliego { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? largoPliego { get; set; }

    public int? pliegosPorHoja { get; set; }

    public int? repeticionesPorPliego { get; set; }

    public int? excedente { get; set; }

    [StringLength(50)]
    public string solicitadoPor { get; set; }

    [InverseProperty("idSolicitudNavigation")]
    public virtual ICollection<lotePliego> lotePliego { get; set; } = new List<lotePliego>();

    [InverseProperty("idSolicitudNavigation")]
    public virtual ICollection<solicitudMaterialesOf> solicitudMaterialesOf { get; set; } = new List<solicitudMaterialesOf>();
}