// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class solicitudMateriales
{
    [Key]
    public int idSolicitud { get; set; }

    [StringLength(50)]
    public string trabajo { get; set; }

    [StringLength(50)]
    public string tipoPreparacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaSolicitud { get; set; }

    [StringLength(50)]
    public string idMaterialSAP { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? anchoHoja { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? largoHoja { get; set; }

    public int? cantidadPorCortar { get; set; }

    [StringLength(25)]
    public string estado { get; set; }

    public int? tiraje { get; set; }

    public int? idMaquina { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? anchoPliego { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? largoPliego { get; set; }

    public int? pliegosPorHoja { get; set; }

    public int? repeticionesPorPliego { get; set; }

    public int? excedente { get; set; }

    [StringLength(50)]
    public string solicitadoPor { get; set; }

    public int? idSap { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? anchoHojaPulg { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? anchoPliegoPulg { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? largoPliegoPulg { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? areaApulg { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? areaA { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? areaBpulg { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? areaB { get; set; }

    [Column(TypeName = "numeric(20, 0)")]
    public decimal? largoHojaPulg { get; set; }

    [StringLength(100)]
    public string compra { get; set; }

    [StringLength(500)]
    public string comentarios { get; set; }

    [StringLength(100)]
    public string interna { get; set; }

    [StringLength(100)]
    public string programada { get; set; }

    [StringLength(100)]
    public string rerefencia { get; set; }

    [StringLength(50)]
    public string direccionCorte { get; set; }

    public bool? archivado { get; set; }

    public bool? cancelado { get; set; }

    [StringLength(50)]
    public string granoHoja { get; set; }

    [StringLength(50)]
    public string subFamiliaSap { get; set; }

    public int? tipoOperacion { get; set; }

    public bool? incluyeProceso { get; set; }

    public string descripcion { get; set; }

    public int? posicion { get; set; }

    public virtual material? MaterialNavigation { get; set; }

    [InverseProperty("idSolicitudNavigation")]
    public virtual ICollection<lotePliego> lotePliego { get; set; } = new List<lotePliego>();

    [InverseProperty("idSolicitudMaterialesNavigation")]
    public virtual ICollection<procesoOf> procesoOf { get; set; } = new List<procesoOf>();

    [InverseProperty("idSolicitudNavigation")]
    public virtual ICollection<solicitudMaterialesOf> solicitudMaterialesOf { get; set; } = new List<solicitudMaterialesOf>();

    [InverseProperty("idSolicitudOrigenNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProceso { get; set; } = new List<transferenciaProceso>();
}