// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idModulo", Name = "MODULO_SUBMODULO_FK")]
public partial class subModulo
{
    [Key]
    public int idSubModulo { get; set; }

    public int? idModulo { get; set; }

    [StringLength(200)]
    public string nombreSubModulo { get; set; }

    [ForeignKey("idModulo")]
    [InverseProperty("subModulo")]
    public virtual modulo idModuloNavigation { get; set; }

    [InverseProperty("idSubModuloNavigation")]
    public virtual ICollection<permiso> permiso { get; set; } = new List<permiso>();

    [InverseProperty("idSubModuloNavigation")]
    public virtual ICollection<permisoTipo> permisoTipo { get; set; } = new List<permisoTipo>();
}