// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("principal_id", "name", Name = "UK_principal_name", IsUnique = true)]
public partial class sysdiagrams
{
    [Required]
    [StringLength(128)]
    public string name { get; set; }

    public int principal_id { get; set; }

    [Key]
    public int diagram_id { get; set; }

    public int? version { get; set; }

    public byte[] definition { get; set; }
}