// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[PrimaryKey("idTablero", "idFlag")]
public partial class tableroFlag
{
    [Key]
    public int idTablero { get; set; }

    [Key]
    public int idFlag { get; set; }

    public int orden { get; set; }

    [ForeignKey("idFlag")]
    [InverseProperty("tableroFlag")]
    public virtual catalogoFlag idFlagNavigation { get; set; }

    [ForeignKey("idTablero")]
    [InverseProperty("tableroFlag")]
    public virtual tablerosOf idTableroNavigation { get; set; }
}