// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idArea", Name = "AREAS_TABLEROS_FK")]
[Index("idMaquina", Name = "MAQUINA_TABLERO_FK")]
public partial class tablerosOf
{
    [Key]
    public int idTablero { get; set; }

    public int? idArea { get; set; }

    public int? idMaquina { get; set; }

    [StringLength(500)]
    public string nombreTablero { get; set; }

    [ForeignKey("idArea")]
    [InverseProperty("tablerosOf")]
    public virtual areas idAreaNavigation { get; set; }

    [ForeignKey("idMaquina")]
    [InverseProperty("tablerosOf")]
    public virtual maquinas idMaquinaNavigation { get; set; }

    [InverseProperty("idTableroNavigation")]
    public virtual ICollection<posturasOf> posturasOf { get; set; } = new List<posturasOf>();

    [InverseProperty("idTableroNavigation")]
    public virtual ICollection<procesoOf> procesoOf { get; set; } = new List<procesoOf>();
}