// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idEstadoOf", Name = "ESTADO_TARJETA_FK")]
public partial class tarjetaOf
{
    [Key]
    public int oF { get; set; }

    public int? oV { get; set; }

    public int? idEstadoOf { get; set; }

    [StringLength(50)]
    public string tipoDeOrden { get; set; }

    [StringLength(500)]
    public string nombreOf { get; set; }

    [StringLength(200)]
    public string productoOf { get; set; }

    [StringLength(50)]
    public string lineaDeNegocio { get; set; }

    [StringLength(200)]
    public string clienteOf { get; set; }

    public string descipcionOf { get; set; }

    [StringLength(50)]
    public string vendedorOf { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? cantidadOf { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaVencimiento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? inicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? finalizacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaUltimaActualizacion { get; set; }

    public int? posicion { get; set; }

    public bool? archivada { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? porcentajeCompletado { get; set; }

    public int? procesosCompletados { get; set; }

    public int? procesosPendientes { get; set; }

    public int? totalProcesos { get; set; }

    public bool? cerrada { get; set; }

    [StringLength(50)]
    public string codArticulo { get; set; }

    [StringLength(50)]
    public string serieOf { get; set; }

    [InverseProperty("oFNavigation")]
    public virtual ICollection<certificadoDeCalidad> certificadoDeCalidad { get; set; } = new List<certificadoDeCalidad>();

    [InverseProperty("oFNavigation")]
    public virtual ICollection<detalleGira> detalleGira { get; set; } = new List<detalleGira>();

    [InverseProperty("oFNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [InverseProperty("ofNavigation")]
    public virtual ICollection<entregasProductoTerminado> entregasProductoTerminado { get; set; } = new List<entregasProductoTerminado>();

    [InverseProperty("oFNavigation")]
    public virtual ICollection<etiquetaOf> etiquetaOf { get; set; } = new List<etiquetaOf>();

    [InverseProperty("oFNavigation")]
    public virtual ICollection<fichaTecnica> fichaTecnica { get; set; } = new List<fichaTecnica>();

    [ForeignKey("idEstadoOf")]
    [InverseProperty("tarjetaOf")]
    public virtual estadosOf idEstadoOfNavigation { get; set; }

    [InverseProperty("oFNavigation")]
    public virtual ICollection<procesoOf> procesoOf { get; set; } = new List<procesoOf>();
}