// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCampo", Name = "CAMPO_TARJETA_FK")]
[Index("idTarjetaOf", Name = "TARJETA_CAMPO_FK")]
public partial class tarjetaCampo
{
    [Key]
    public int tcampoId { get; set; }

    public int? idTarjetaOf { get; set; }

    public int? idCampo { get; set; }

    [StringLength(256)]
    public string valorTexto { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? valorNumero { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? valorFecha { get; set; }

    public string valorLista { get; set; }

    public bool? valorCasilla { get; set; }

    [ForeignKey("idCampo")]
    [InverseProperty("tarjetaCampo")]
    public virtual camposPersonalizados idCampoNavigation { get; set; }

    [ForeignKey("idTarjetaOf")]
    [InverseProperty("tarjetaCampo")]
    public virtual tarjetaOf idTarjetaOfNavigation { get; set; }
}