// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idCampo", Name = "CAMPO_TARJETA_FK")]
[Index("idProceso", Name = "TARJETA_CAMPO_FK")]
public partial class tarjetaCampo
{
    [Key]
    public int idCamposTarjeta { get; set; }

    public int? idProceso { get; set; }

    public int? idCampo { get; set; }

    [StringLength(254)]
    public string valorTexto { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? valorNumero { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? valorFecha { get; set; }

    [StringLength(1)]
    public string valorLista { get; set; }

    public bool? valorCasilla { get; set; }

    [ForeignKey("idCampo")]
    [InverseProperty("tarjetaCampo")]
    public virtual camposPersonalizados idCampoNavigation { get; set; }

    [ForeignKey("idProceso")]
    [InverseProperty("tarjetaCampo")]
    public virtual procesoOf idProcesoNavigation { get; set; }
}