// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sistema_Produccion_3_Backend.Models
{
    public partial class TimeInListResult
    {
        public int? proceso_id { get; set; }
        [StringLength(100)]
        public string estado { get; set; }
        [Column("total_horas", TypeName = "decimal(10,2)")]
        public decimal? total_horas { get; set; }
    }
}
