// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetallePegado", Name = "TIPO_PEGAMENTO_FK")]
public partial class tipoPega
{
    [Key]
    public int idTipoPega { get; set; }

    public int? idDetallePegado { get; set; }

    [Column("tipoPega")]
    [StringLength(50)]
    public string tipoPega1 { get; set; }

    [StringLength(50)]
    public string lote { get; set; }

    [StringLength(50)]
    public string vence { get; set; }

    [StringLength(50)]
    public string marca { get; set; }

    [StringLength(50)]
    public string proveedor { get; set; }

    [StringLength(50)]
    public string tolerancia { get; set; }

    [ForeignKey("idDetallePegado")]
    [InverseProperty("tipoPega")]
    public virtual detallePegado idDetallePegadoNavigation { get; set; }
}