// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetalleTroquelado", Name = "PLECA_TROQUEL_FK")]
public partial class tipoPleca
{
    [Key]
    public int idTipoPleca { get; set; }

    public int? idDetalleTroquelado { get; set; }

    [StringLength(50)]
    public string tipoDePleca { get; set; }

    [StringLength(50)]
    public string medida { get; set; }

    public bool? lineaRecta { get; set; }

    [Column("45grados")]
    public bool? _45grados { get; set; }

    [StringLength(50)]
    public string tamanoAgujero { get; set; }

    public bool? agujero { get; set; }

    public bool? basuraMaterial { get; set; }

    [ForeignKey("idDetalleTroquelado")]
    [InverseProperty("tipoPleca")]
    public virtual detalleTroquelado idDetalleTroqueladoNavigation { get; set; }
}