// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetallePegado", Name = "TIPO_PEGADO_FK")]
public partial class tipoPegado
{
    [Key]
    public int idTipoPegado { get; set; }

    public int? idDetallePegado { get; set; }

    [Column("tipoPegado")]
    [StringLength(50)]
    public string tipoPegado1 { get; set; }

    public bool? disco { get; set; }

    public bool? pistola { get; set; }

    [ForeignKey("idDetallePegado")]
    [InverseProperty("tipoPegado")]
    public virtual detallePegado idDetallePegadoNavigation { get; set; }
}