// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idDetalleTroquelado", Name = "ACABADO_TROQUEL_FK")]
public partial class tipoAcabado
{
    [Key]
    public int idTipoAcabado { get; set; }

    public int? idDetalleTroquelado { get; set; }

    [Column("tipoAcabado")]
    [StringLength(50)]
    public string tipoAcabado1 { get; set; }

    [StringLength(20)]
    public string color { get; set; }

    [StringLength(50)]
    public string proveedor { get; set; }

    [StringLength(50)]
    public string codigo { get; set; }

    [StringLength(50)]
    public string lote { get; set; }

    [StringLength(50)]
    public string presionMaquina { get; set; }

    [Column(TypeName = "numeric(20, 2)")]
    public decimal? velocidadMaquina { get; set; }

    [StringLength(50)]
    public string temperaturaLamina { get; set; }

    [StringLength(50)]
    public string cantidad { get; set; }

    [StringLength(50)]
    public string tipoFoil { get; set; }

    public bool? macho { get; set; }

    public bool? hembra { get; set; }

    [ForeignKey("idDetalleTroquelado")]
    [InverseProperty("tipoAcabado")]
    public virtual detalleTroquelado idDetalleTroqueladoNavigation { get; set; }
}