// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class tipoCaso
{
    [Key]
    public int idTipoCaso { get; set; }

    [Required]
    [StringLength(60)]
    public string nombre { get; set; }

    [StringLength(250)]
    public string descripcion { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idTipoCasoNavigation")]
    public virtual ICollection<casoCalidad> casoCalidad { get; set; } = new List<casoCalidad>();
}