// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class tipoEventoBitacora
{
    [Key]
    public int idTipoEvento { get; set; }

    [Required]
    [StringLength(60)]
    public string nombre { get; set; }

    public bool activo { get; set; }

    [InverseProperty("idTipoEventoNavigation")]
    public virtual ICollection<bitacoraCaso> bitacoraCaso { get; set; } = new List<bitacoraCaso>();
}