// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("unidadBase", Name = "FK_UNIDAD_BASE")]
public partial class tipoComponente
{
    [Key]
    public int idTipoComponente { get; set; }

    [StringLength(80)]
    public string codigo { get; set; }

    [StringLength(250)]
    public string descripcion { get; set; }

    public int? unidadBase { get; set; }

    public bool? esFinal { get; set; }

    [InverseProperty("tipoComponenteNavigation")]
    public virtual ICollection<componenteProduccion> componenteProducciontipoComponenteNavigation { get; set; } = new List<componenteProduccion>();

    [InverseProperty("tipoSalidaNavigation")]
    public virtual ICollection<componenteProduccion> componenteProducciontipoSalidaNavigation { get; set; } = new List<componenteProduccion>();

    [InverseProperty("tipoComponenteNavigation")]
    public virtual ICollection<configuracionProceso> configuracionProcesotipoComponenteNavigation { get; set; } = new List<configuracionProceso>();

    [InverseProperty("tipoEntradaNavigation")]
    public virtual ICollection<configuracionProceso> configuracionProcesotipoEntradaNavigation { get; set; } = new List<configuracionProceso>();

    [InverseProperty("tipoSalidaNavigation")]
    public virtual ICollection<configuracionProceso> configuracionProcesotipoSalidaNavigation { get; set; } = new List<configuracionProceso>();

    [InverseProperty("tipoSemielaboradoNavigation")]
    public virtual ICollection<transferenciaProceso> transferenciaProceso { get; set; } = new List<transferenciaProceso>();

    [ForeignKey("unidadBase")]
    [InverseProperty("tipoComponente")]
    public virtual unidadesMedida unidadBaseNavigation { get; set; }
}