// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class tipoReporte
{
    [Key]
    public int idTipoReporte { get; set; }

    [StringLength(200)]
    public string nombreTipoReporte { get; set; }

    [InverseProperty("idTipoReporteNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();
}