// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class tipoCierre
{
    [Key]
    public int idTipoCierre { get; set; }

    [StringLength(200)]
    public string nombreTipoCierre { get; set; }

    [InverseProperty("idTipoCierreNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();
}