// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("areaDestino", Name = "AREA_DESTINO_FK")]
[Index("areaOrigen", Name = "AREA_ORIGEN_FK")]
[Index("idDestino", Name = "ID_DESTINO_FK")]
[Index("idOrigen", Name = "ID_ORIGEN_FK")]
[Index("idProduccion", Name = "ID_PRODUCCION_ORIGEN_FK")]
[Index("idLote", Name = "LOTEPLIEGO_TRANSFERENCIAPROCESO_FK")]
[Index("oFDestino", Name = "OF_DESTINO_FK")]
[Index("idSolicitudOrigen", Name = "SOLICITUD_ORIGEN_FK")]
[Index("enviadoPor", Name = "TRANSFERECIA_ENVIADA_POR_FK")]
[Index("recibidoPor", Name = "TRANSFERECIA_RECIBIDA_POR_FK")]
public partial class transferenciaProceso
{
    [Key]
    public int idTransferencia { get; set; }

    public int? idLote { get; set; }

    [StringLength(50)]
    public string unidadDeMedida { get; set; }

    [StringLength(50)]
    public string tipo { get; set; }

    [StringLength(25)]
    public string estado { get; set; }

    public int? idOrigen { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaEnvio { get; set; }

    [StringLength(50)]
    public string enviadoPor { get; set; }

    public int? cantidadEnviada { get; set; }

    public int? idDestino { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaRecepcion { get; set; }

    [StringLength(50)]
    public string recibidoPor { get; set; }

    public int? cantidadConfirmada { get; set; }

    [StringLength(150)]
    public string observaciones { get; set; }

    public int? idProduccion { get; set; }

    public int? areaOrigen { get; set; }

    public int? areaDestino { get; set; }

    public int? oFDestino { get; set; }

    public int? idSolicitudOrigen { get; set; }

    [StringLength(255)]
    public string idMaterialSAP { get; set; }

    [StringLength(500)]
    public string materialDescripcion { get; set; }

    public int? tipoSemielaborado { get; set; }

    [ForeignKey("areaDestino")]
    [InverseProperty("transferenciaProcesoareaDestinoNavigation")]
    public virtual areas areaDestinoNavigation { get; set; }

    [ForeignKey("areaOrigen")]
    [InverseProperty("transferenciaProcesoareaOrigenNavigation")]
    public virtual areas areaOrigenNavigation { get; set; }

    [InverseProperty("idTransferenciaNavigation")]
    public virtual ICollection<detalleReporte> detalleReporte { get; set; } = new List<detalleReporte>();

    [ForeignKey("enviadoPor")]
    [InverseProperty("transferenciaProcesoenviadoPorNavigation")]
    public virtual usuario enviadoPorNavigation { get; set; }

    [ForeignKey("idDestino")]
    [InverseProperty("transferenciaProcesoidDestinoNavigation")]
    public virtual procesoOf idDestinoNavigation { get; set; }

    [ForeignKey("idLote")]
    [InverseProperty("transferenciaProceso")]
    public virtual lotePliego idLoteNavigation { get; set; }

    [ForeignKey("idOrigen")]
    [InverseProperty("transferenciaProcesoidOrigenNavigation")]
    public virtual procesoOf idOrigenNavigation { get; set; }

    [ForeignKey("idProduccion")]
    [InverseProperty("transferenciaProceso")]
    public virtual detalleReporte idProduccionNavigation { get; set; }

    [ForeignKey("idSolicitudOrigen")]
    [InverseProperty("transferenciaProceso")]
    public virtual solicitudMateriales idSolicitudOrigenNavigation { get; set; }

    [ForeignKey("oFDestino")]
    [InverseProperty("transferenciaProceso")]
    public virtual tarjetaOf oFDestinoNavigation { get; set; }

    [ForeignKey("recibidoPor")]
    [InverseProperty("transferenciaProcesorecibidoPorNavigation")]
    public virtual usuario recibidoPorNavigation { get; set; }

    [ForeignKey("tipoSemielaborado")]
    [InverseProperty("transferenciaProceso")]
    public virtual tipoComponente tipoSemielaboradoNavigation { get; set; }
}