// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class turnoAuditoria
{
    [Key]
    public int idTurnoAuditor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(50)]
    public string auditor { get; set; }

    public int? turno { get; set; }

    public int? estado { get; set; }

    public int? tipoReporte { get; set; }

    [StringLength(50)]
    public string aprobadoPor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaAprobacion { get; set; }

    public bool? cancelado { get; set; }

    public bool? archivado { get; set; }

    [ForeignKey("aprobadoPor")]
    [InverseProperty("turnoAuditoriaaprobadoPorNavigation")]
    public virtual usuario aprobadoPorNavigation { get; set; }

    [ForeignKey("auditor")]
    [InverseProperty("turnoAuditoriaauditorNavigation")]
    public virtual usuario auditorNavigation { get; set; }

    [InverseProperty("turnoAuditoriaNavigation")]
    public virtual ICollection<auditoriaProceso> auditoriaProceso { get; set; } = new List<auditoriaProceso>();

    [ForeignKey("estado")]
    [InverseProperty("turnoAuditoria")]
    public virtual estadosReporte estadoNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("turnoAuditoria")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }

    [ForeignKey("turno")]
    [InverseProperty("turnoAuditoria")]
    public virtual turnos turnoNavigation { get; set; }

    [InverseProperty("turnoNavigation")]
    public virtual ICollection<validacionArranque> validacionArranque { get; set; } = new List<validacionArranque>();
}