// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class turnosOperativos
{
    [Key]
    public int idTurno { get; set; }

    [StringLength(50)]
    public string turno { get; set; }

    public TimeOnly? horaInicio { get; set; }

    public TimeOnly? horaFin { get; set; }

    [InverseProperty("idTurnoNavigation")]
    public virtual ICollection<turnosOperativosArea> turnosOperativosArea { get; set; } = new List<turnosOperativosArea>();
}