// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class turnos
{
    [Key]
    public int id { get; set; }

    [StringLength(25)]
    public string turno { get; set; }

    public TimeOnly? horaInicio { get; set; }

    public TimeOnly? horaFinal { get; set; }

    [InverseProperty("idTurnoNavigation")]
    public virtual ICollection<confirmacionPreliminar> confirmacionPreliminar { get; set; } = new List<confirmacionPreliminar>();

    [InverseProperty("turnoNavigation")]
    public virtual ICollection<turnoAuditoria> turnoAuditoria { get; set; } = new List<turnoAuditoria>();
}