// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idRol", Name = "ROL_USUARIO_FK")]
public partial class usuario
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string user { get; set; }

    public int? idRol { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string status { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string password { get; set; }

    [StringLength(200)]
    public string nombres { get; set; }

    [StringLength(200)]
    public string apellidos { get; set; }

    [StringLength(200)]
    public string email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaDeCreacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ultimaActualizacion { get; set; }

    [StringLength(100)]
    public string actualizadoPor { get; set; }

    [InverseProperty("userNavigation")]
    public virtual ICollection<disenador> disenador { get; set; } = new List<disenador>();

    [ForeignKey("idRol")]
    [InverseProperty("usuario")]
    public virtual rol idRolNavigation { get; set; }

    [InverseProperty("userNavigation")]
    public virtual ICollection<movimientoOf> movimientoOf { get; set; } = new List<movimientoOf>();

    [InverseProperty("userNavigation")]
    public virtual ICollection<operador> operador { get; set; } = new List<operador>();

    [InverseProperty("userNavigation")]
    public virtual ICollection<refreshToken> refreshToken { get; set; } = new List<refreshToken>();
}