// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idArea", Name = "AREA_USUARIO_FK")]
[Index("idCargo", Name = "CARGO_USUARIO_FK")]
[Index("idRol", Name = "ROL_USUARIO_FK")]
public partial class usuario
{
    [Key]
    [StringLength(50)]
    public string user { get; set; }

    public int? idRol { get; set; }

    public int? idCargo { get; set; }

    public int? idArea { get; set; }

    public bool? status { get; set; }

    [StringLength(200)]
    public string password { get; set; }

    [StringLength(200)]
    public string nombres { get; set; }

    [StringLength(200)]
    public string apellidos { get; set; }

    [StringLength(200)]
    public string email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaDeCreacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ultimaActualizacion { get; set; }

    [StringLength(50)]
    public string actualizadoPor { get; set; }

    [InverseProperty("userNavigation")]
    public virtual ICollection<asignacion> asignacion { get; set; } = new List<asignacion>();

    [InverseProperty("userNavigation")]
    public virtual ICollection<auditoriaDeCalidad> auditoriaDeCalidad { get; set; } = new List<auditoriaDeCalidad>();

    [ForeignKey("idArea")]
    [InverseProperty("usuario")]
    public virtual areas idAreaNavigation { get; set; }

    [ForeignKey("idCargo")]
    [InverseProperty("usuario")]
    public virtual cargo idCargoNavigation { get; set; }

    [ForeignKey("idRol")]
    [InverseProperty("usuario")]
    public virtual rol idRolNavigation { get; set; }

    [InverseProperty("usuarioNavigation")]
    public virtual ICollection<pausasMaquina> pausasMaquina { get; set; } = new List<pausasMaquina>();

    [InverseProperty("userNavigation")]
    public virtual ICollection<permisoMaquina> permisoMaquina { get; set; } = new List<permisoMaquina>();

    [InverseProperty("userNavigation")]
    public virtual ICollection<refreshToken> refreshToken { get; set; } = new List<refreshToken>();

    [InverseProperty("operadorNavigation")]
    public virtual ICollection<reportesDeOperadores> reportesDeOperadores { get; set; } = new List<reportesDeOperadores>();

    [InverseProperty("operadorNavigation")]
    public virtual ICollection<sesionOperador> sesionOperador { get; set; } = new List<sesionOperador>();
}