// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

public partial class valeBobina
{
    [Key]
    public int idVale { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? pesoInicial { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? pesoFinal { get; set; }

    [StringLength(25)]
    public string idMaterial { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechaCreacion { get; set; }

    [StringLength(30)]
    public string loteBobinaSAP { get; set; }

    [StringLength(150)]
    public string proveedorBobina { get; set; }

    [Column(TypeName = "numeric(38, 2)")]
    public decimal? anchoBobina { get; set; }

    [StringLength(200)]
    public string descripcionBobina { get; set; }

    [StringLength(100)]
    public string calibreBobina { get; set; }

    [StringLength(100)]
    public string gramajeBobina { get; set; }

    public bool? entregaParcial { get; set; }

    public int? tipoReporte { get; set; }

    public int? estado { get; set; }

    [StringLength(500)]
    public string observaciones { get; set; }

    [ForeignKey("estado")]
    [InverseProperty("valeBobina")]
    public virtual estadosReporte estadoNavigation { get; set; }

    [ForeignKey("idMaterial")]
    [InverseProperty("valeBobina")]
    public virtual material idMaterialNavigation { get; set; }

    [ForeignKey("tipoReporte")]
    [InverseProperty("valeBobina")]
    public virtual tipoReporte tipoReporteNavigation { get; set; }

    [InverseProperty("idValeNavigation")]
    public virtual ICollection<valeBobinaCorteEstado> valeBobinaCorteEstado { get; set; } = new List<valeBobinaCorteEstado>();
}