// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[Index("idReporteAuditoria", Name = "VARIABLES_FK")]
public partial class variablesDeAgua
{
    [Key]
    public int idVariables { get; set; }

    public int? idReporteAuditoria { get; set; }

    [StringLength(50)]
    public string ph { get; set; }

    [StringLength(50)]
    public string cond { get; set; }

    [StringLength(50)]
    public string acl { get; set; }

    [StringLength(50)]
    public string tem { get; set; }

    [StringLength(50)]
    public string vis { get; set; }

    [ForeignKey("idReporteAuditoria")]
    [InverseProperty("variablesDeAgua")]
    public virtual reporteDeAuditoria idReporteAuditoriaNavigation { get; set; }
}