// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_Produccion_3_Backend.Models;

[PrimaryKey("idVariable", "idUnidad")]
public partial class variableUnidadMedida
{
    [Key]
    public int idVariable { get; set; }

    [Key]
    public int idUnidad { get; set; }

    public bool? predeterminada { get; set; }

    public int? orden { get; set; }

    [ForeignKey("idUnidad")]
    [InverseProperty("variableUnidadMedida")]
    public virtual unidadesMedida idUnidadNavigation { get; set; }

    [ForeignKey("idVariable")]
    [InverseProperty("variableUnidadMedida")]
    public virtual variablesTecnicas idVariableNavigation { get; set; }
}